# 01 — Data Collection

This notebook pulls raw shot log data from the NBA API for individual players.
A shot log is a record of every field goal attempt in a season — location on the court, whether it went in, shot type, quarter, defender distance, and more.

We'll save every API response to a local cache folder so we never have to re-download the same data twice.

**Section 1 covers:**
- Setting up our imports
- Building a reusable fetch function that checks the cache before hitting the API
- Testing it with LeBron James (2023–24 regular season)

## 1.1 — Imports

We need a handful of standard libraries plus `nba_api`, the community-built Python wrapper around NBA.com's stats endpoints.

- `os` / `pathlib` — create folders and check if files exist on disk
- `time` / `random` — controlled delays between API calls to avoid rate-limiting; `random` lets us vary the delay so requests don't arrive at perfectly regular intervals (which triggers some firewalls)
- `pandas` — store and manipulate the shot data as a DataFrame
- `requests.exceptions` — lets us catch specific network errors (timeouts, dropped connections) for the retry logic we'll build into the fetch function
- `nba_api` — `ShotChartDetail` for shot-by-shot data; `CommonAllPlayers` for the full league roster; `players` (static) for quick name-to-ID lookups

In [1]:
import os
import time
import random
import pandas as pd

from pathlib import Path
from requests.exceptions import ReadTimeout, ConnectionError as ConnError
from nba_api.stats.endpoints import ShotChartDetail, CommonAllPlayers
from nba_api.stats.static import players

print("Imports loaded successfully.")
print(f"pandas version: {pd.__version__}")

Imports loaded successfully.
pandas version: 3.0.3

## 1.2 — Directory Setup

We'll store cached API responses in `data/cache/`. Each file is named after the player ID and season so it's easy to find later (e.g., `shots_2544_2023-24.csv`).

This cell just ensures the folder exists before we try to write into it.

In [2]:
# Resolve paths relative to the notebook's location so this works
# regardless of where Jupyter was launched from.
NOTEBOOK_DIR = Path().resolve()
PROJECT_ROOT = NOTEBOOK_DIR.parent  # one level up from /notebooks/

CACHE_DIR = PROJECT_ROOT / "data" / "cache"
RAW_DIR   = PROJECT_ROOT / "data" / "raw"

CACHE_DIR.mkdir(parents=True, exist_ok=True)
RAW_DIR.mkdir(parents=True, exist_ok=True)

print(f"Project root : {PROJECT_ROOT}")
print(f"Cache folder : {CACHE_DIR}")
print(f"Raw folder   : {RAW_DIR}")

Project root : /Users/narayanlekhi/Documents/GitHub/nba-shot-analytics
Cache folder : /Users/narayanlekhi/Documents/GitHub/nba-shot-analytics/data/cache
Raw folder   : /Users/narayanlekhi/Documents/GitHub/nba-shot-analytics/data/raw

## 1.3 — Player ID Lookup

The NBA API identifies every player by a numeric ID, not a name. LeBron James's ID is `2544`.

The `nba_api.stats.static.players` module ships with a full player list built in — no network request needed. We'll write a small helper that takes a name and returns the ID, so we don't have to memorize numbers.

In [3]:
def get_player_id(full_name: str) -> int:
    """
    Look up an NBA player's numeric ID by their full name.
    Raises a clear error if the name isn't found, rather than returning None silently.
    """
    matches = players.find_players_by_full_name(full_name)

    if not matches:
        raise ValueError(
            f"No player found for '{full_name}'. "
            "Check spelling — the API expects the full legal name (e.g. 'LeBron James')."
        )

    # find_players_by_full_name can return multiple partial matches;
    # take the first exact-ish match (results are sorted by relevance).
    player = matches[0]
    print(f"Found: {player['full_name']}  |  ID: {player['id']}  |  Active: {player['is_active']}")
    return player["id"]


# Test it
lebron_id = get_player_id("LeBron James")

Found: LeBron James  |  ID: 2544  |  Active: True

## 1.4 — Fetch Function with Caching and Retry Logic

This is the core fetch function. It now does three things:

1. **Check the cache first.** If the player's shot log for this season is already on disk, load it immediately — no API call, no delay.
2. **Randomized delay before fresh requests.** A random 3–5 second pause before each new API call avoids hitting NBA.com's rate limiter, which is more likely to block evenly-spaced automated requests than irregular ones.
3. **Retry on transient network errors.** If the request fails with a timeout or dropped connection, wait 5 seconds and try again, up to 3 times. On a final failure it returns `None` so the calling loop can log it and continue rather than crashing.

The function returns `None` (rather than raising an exception) so the multi-player loop in Section 2 can catch failures gracefully and move on.

In [4]:
def fetch_shot_log(
    player_id: int,
    season: str,
    cache_dir: Path = None,
    max_retries: int = 3,
) -> pd.DataFrame | None:
    """
    Return a DataFrame of every field goal attempt for a player in a given season.

    Checks data/cache/ first. On a cache miss, waits a random 3–5 seconds then
    calls the NBA Aerrors.
    Returns None if all retries are exhausted.

    Args:
        player_id:   NBA player ID (e.g. 2544 for LeBron James)
        season:      Season string in "YYYY-YY" format (e.g. "2025-26")
        cache_dir:   Folder for cached CSVs; defaults to CACHE_DIR
        max_retries: How many times to retry on a timeout or connection error

    Returns:
        pandas DataFrame with one row per shot attempt, or None on failure
    """
    if cache_dir is None:
        cache_dir = CACHE_DIR

    cache_file = cache_dir / f"shots_{player_id}_{season}.csv"

    # --- Cache hit: load from disk, no API call needed ---
    if cache_file.exists():
        return pd.read_csv(cache_file)

    # --- Cache miss: randomized delay then API call ---
    delay = random.uniform(3.0, 5.0)
    time.sleep(delay)

    for attempt in range(1, max_retries + 1):
        try:
            shot_chart = ShotChartDetail(
                team_id=0,
                player_id=player_id,
                season_nullable=season,
                season_type_all_star="Regular Season",
                context_measure_simple="FGA",
            )
            df = shot_chart.get_data_frames()[0]
            df.to_csv(cache_file, index=False)
            return df

        except (ReadTimeout, ConnError) as e:
            # Transient network error — eligible for retry
            if attempt < max_retries:
                print(f"      [retry {attempt}/{max_retries}] {type(e).__name__} — waiting 5s...")
                time.sleep(5.0)
            else:
                print(f"      [failed] {type(e).__name__} after {max_retries} attempts")
                return None

        except Exception as e:
            # Unexpected error — don't retry, just log and bail
            print(f"      [error] {type(e).__name__}: {e}")
            return None

## 1.5 — Test: LeBron James, 2025–26 Season

We call the function once before the full-league loop to confirm it works correctly under the new season and retry logic. If LeBron's 2025–26 cache file doesn't exist yet, this will make one API call (with the 3–5 second delay). If it does exist, it loads instantly from disk.

In [5]:
SEASON = "2025-26"

lebron_id    = get_player_id("LeBron James")
lebron_shots = fetch_shot_log(player_id=lebron_id, season=SEASON)

if lebron_shots is None:
    print("Fetch failed — check your network connection and re-run.")
else:
    print(f"\nShape: {lebron_shots.shape[0]:,} rows × {lebron_shots.shape[1]} columns")
    print("\nColumns:")
    print(lebron_shots.columns.tolist())

Found: LeBron James  |  ID: 2544  |  Active: True

Shape: 919 rows × 24 columns

Columns:
['GRID_TYPE', 'GAME_ID', 'GAME_EVENT_ID', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_NAME', 'PERIOD', 'MINUTES_REMAINING', 'SECONDS_REMAINING', 'EVENT_TYPE', 'ACTION_TYPE', 'SHOT_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'SHOT_DISTANCE', 'LOC_X', 'LOC_Y', 'SHOT_ATTEMPTED_FLAG', 'SHOT_MADE_FLAG', 'GAME_DATE', 'HTM', 'VTM']

## 1.6 — Quick Sanity Check

Before we close out Section 1, let's verify a few things:
- The data is actually LeBron's (check `PLAYER_NAME`)
- The season looks right (check `SEASON_ID`)
- We have a mix of made and missed shots (not all zeros in `SHOT_MADE_FLAG`)

In [6]:
# Spot-check: who and what season is this?
print("Player name (unique values):", lebron_shots["PLAYER_NAME"].unique())

# SEASON_ID is not returned by ShotChartDetail; use GAME_DATE instead
print("Date range:", lebron_shots["GAME_DATE"].min(), "→", lebron_shots["GAME_DATE"].max())

# Counts of made vs missed shots
shot_counts = lebron_shots["SHOT_MADE_FLAG"].value_counts().rename({0: "Missed", 1: "Made"})
print("\nShot outcome counts:")
print(shot_counts)
print(f"\nImplied FG%: {shot_counts['Made'] / shot_counts.sum():.1%}")

Player name (unique values): <StringArray>
['LeBron James']
Length: 1, dtype: str
Date range: 20251118 → 20260412

Shot outcome counts:
SHOT_MADE_FLAG
Made      473
Missed    446
Name: count, dtype: int64

Implied FG%: 51.5%

## Section 2 — Fetching the Full 2025–26 League Roster

Instead of a hand-picked list of five players, we now pull shot logs for every player who appeared in the 2025–26 regular season.

The plan:
1. Fetch the full active roster from the NBA API's `CommonAllPlayers` endpoint
2. Loop through every player, using the cache to skip anyone already downloaded
3. Retry up to 3 times on network errors; log any players who ultimately fail
4. Combine all successful results into one DataFrame and save to `data/raw/shots_2025_26.csv`

**Estimated runtime:** With ~400–500 active players and a 3–5 second delay per fresh request, expect 30–60 minutes on a first run. Subsequent runs (all cache hits) complete in under a minute. If the script is interrupted, just re-run — the cache preserves every completed player automatically.

### 2.1 — Fetch the Active Player Roster

`CommonAllPlayers` returns a table of every player in NBA history. Passing `is_only_current_season=1` restricts it to the season we specify. We then filter to players where `GAMES_PLAYED_FLAG == "Y"` — this drops players who were on a roster but never appeared in a game and would return an empty shot log anyway.

We print a count so we know how many API calls the fetch loop will need to make on a cold run.

In [7]:
print(f"Fetching active roster for {SEASON}...")

roster_response = CommonAllPlayers(
    is_only_current_season=1,
    league_id="00",
    season=SEASON,
)
all_players_df = roster_response.get_data_frames()[0]

# Keep only players who actually appeared in at least one game
active_players_df = all_players_df[all_players_df["GAMES_PLAYED_FLAG"] == "Y"].copy()
active_players_df = active_players_df.reset_index(drop=True)

print(f"\nTotal players in API response : {len(all_players_df):,}")
print(f"Players with games played      : {len(active_players_df):,}")
print(f"\nFirst 10 players:")
display(
    active_players_df[["PERSON_ID", "DISPLAY_FIRST_LAST", "TEAM_ABBREVIATION"]]
    .head(10)
)

Fetching active roster for 2025-26...

Total players in API response : 582
Players with games played      : 582

First 10 players:

   PERSON_ID        DISPLAY_FIRST_LAST TEAM_ABBREVIATION
0    1630173          Precious Achiuwa               SAC
1     203500              Steven Adams               HOU
2    1628389               Bam Adebayo               MIA
3    1630534              Ochai Agbaji               BKN
4    1630583              Santi Aldama               MEM
5    1641725            Trey Alexander               NOP
6    1629638  Nickeil Alexander-Walker               ATL
7    1628960             Grayson Allen               PHX
8    1628386             Jarrett Allen               CLE
9    1630631             Jose Alvarado               NYK

### 2.2 — Fetch Shot Logs for All Players

The loop iterates over every player in the roster. For each one:

- **Cache hit** → load silently from disk, no output, no delay
- **Cache miss** → call `fetch_shot_log()`, which applies the 3–5 second randomized delay and up to 3 retries automatically
- **Empty result** → player had 0 field goal attempts (rare: some two-way or end-of-bench players), logged separately and skipped
- **None result** → all retries failed, player added to `failed_players` list

The `tqdm` progress bar shows overall progress. Intermediate `tqdm.write()` calls print status lines without corrupting the bar.

If you need to stop mid-run, `Ctrl+C` is safe — every player fetched so far is already saved to the cache. Re-running the cell will skip all cached players and resume from where it stopped.

In [8]:
from tqdm import tqdm

all_shot_logs   = []   # one DataFrame per player (non-empty)
failed_players  = []   # players where all retries failed
skipped_players = []   # players with 0 shot attempts
cache_hits      = 0

for _, player_row in tqdm(
    active_players_df.iterrows(),
    total=len(active_players_df),
    desc="Fetching shot logs",
):
    name      = player_row["DISPLAY_FIRST_LAST"]
    player_id = int(player_row["PERSON_ID"])

    cache_file = CACHE_DIR / f"shots_{player_id}_{SEASON}.csv"

    # --- Fast path: cache hit ---
    # Read silently and move on — no print, no delay.
    if cache_file.exists():
        cache_hits += 1
        df = pd.read_csv(cache_file)
        if len(df) > 0:
            df["NAME"] = name
            all_shot_logs.append(df)
        continue

    # --- Slow path: API call (delay + retry handled inside fetch_shot_log) ---
    df = fetch_shot_log(player_id=player_id, season=SEASON)

    if df is None:
        failed_players.append({"name": name, "id": player_id})
        tqdm.write(f"  [FAILED]  {name}")

    elif len(df) == 0:
        skipped_players.append(name)
        tqdm.write(f"  [skip]    {name} — 0 shot attempts recorded")

    else:
        df["NAME"] = name
        all_shot_logs.append(df)
        tqdm.write(f"  [done]    {name} — {len(df):,} shots")

print(f"\nLoop complete.")
print(f"  Loaded from cache : {cache_hits}")
print(f"  Fetched via API   : {len(all_shot_logs) + len(failed_players) + len(skipped_players) - cache_hits}")
print(f"  Successful        : {len(all_shot_logs)}")
print(f"  Skipped (0 shots) : {len(skipped_players)}")
print(f"  Failed            : {len(failed_players)}")

Fetching shot logs:   0%|                      | 1/582 [00:05<56:08,  5.80s/it]

  [done]    Precious Achiuwa — 598 shots

Fetching shot logs:   0%|                      | 2/582 [00:10<50:59,  5.27s/it]

  [done]    Steven Adams — 139 shots

Fetching shot logs:   1%|                      | 3/582 [00:15<49:11,  5.10s/it]

  [done]    Bam Adebayo — 1,145 shots

Fetching shot logs:   1%|▏                     | 4/582 [00:20<48:26,  5.03s/it]

  [done]    Ochai Agbaji — 280 shots

Fetching shot logs:   1%|▏                     | 5/582 [00:25<48:33,  5.05s/it]

  [done]    Santi Aldama — 476 shots

Fetching shot logs:   1%|▏                     | 6/582 [00:30<48:44,  5.08s/it]

  [done]    Trey Alexander — 37 shots

Fetching shot logs:   1%|▎                     | 7/582 [00:35<49:04,  5.12s/it]

  [done]    Nickeil Alexander-Walker — 1,195 shots

Fetching shot logs:   1%|▎                     | 8/582 [00:40<48:38,  5.09s/it]

  [done]    Grayson Allen — 667 shots

Fetching shot logs:   2%|▎                     | 9/582 [00:45<45:51,  4.80s/it]

  [done]    Jarrett Allen — 528 shots

Fetching shot logs:   2%|▎                    | 10/582 [00:50<48:35,  5.10s/it]

  [done]    Jose Alvarado — 449 shots

Fetching shot logs:   2%|▍                    | 11/582 [00:55<47:40,  5.01s/it]

  [done]    Kyle Anderson — 202 shots

Fetching shot logs:   2%|▍                    | 12/582 [01:01<49:11,  5.18s/it]

  [done]    Alex Antetokounmpo — 8 shots

Fetching shot logs:   2%|▍                    | 13/582 [01:07<51:54,  5.47s/it]

  [done]    Giannis Antetokounmpo — 598 shots

Fetching shot logs:   2%|▌                    | 14/582 [01:11<48:39,  5.14s/it]

  [done]    Thanasis Antetokounmpo — 32 shots

Fetching shot logs:   3%|▌                    | 15/582 [01:15<45:41,  4.84s/it]

  [done]    Cole Anthony — 231 shots

Fetching shot logs:   3%|▌                    | 16/582 [01:20<44:47,  4.75s/it]

  [done]    OG Anunoby — 804 shots

Fetching shot logs:   3%|▌                    | 17/582 [01:24<43:07,  4.58s/it]

  [done]    Deni Avdija — 1,064 shots

Fetching shot logs:   3%|▋                    | 18/582 [01:30<46:21,  4.93s/it]

  [done]    Deandre Ayton — 601 shots

Fetching shot logs:   3%|▋                    | 19/582 [01:34<44:58,  4.79s/it]

  [done]    Marvin Bagley III — 411 shots

Fetching shot logs:   3%|▋                    | 20/582 [01:39<45:33,  4.86s/it]

  [done]    Ace Bailey — 892 shots

Fetching shot logs:   4%|▊                    | 21/582 [01:45<46:41,  4.99s/it]

  [done]    Adama Bal — 68 shots

Fetching shot logs:   4%|▊                    | 22/582 [01:49<43:40,  4.68s/it]

  [done]    Patrick Baldwin Jr. — 27 shots

Fetching shot logs:   4%|▊                    | 23/582 [01:55<47:15,  5.07s/it]

  [done]    LaMelo Ball — 1,244 shots

Fetching shot logs:   4%|▊                    | 24/582 [01:59<44:06,  4.74s/it]

  [done]    Lonzo Ball — 176 shots

Fetching shot logs:   4%|▉                    | 25/582 [02:04<46:37,  5.02s/it]

  [done]    Mo Bamba — 11 shots

Fetching shot logs:   4%|▉                    | 26/582 [02:09<45:38,  4.92s/it]

  [done]    Paolo Banchero — 1,152 shots

Fetching shot logs:   5%|▉                    | 27/582 [02:14<46:00,  4.97s/it]

  [done]    Desmond Bane — 1,205 shots

Fetching shot logs:   5%|█                    | 28/582 [02:18<42:25,  4.59s/it]

  [done]    Dalano Banton — 12 shots

Fetching shot logs:   5%|█                    | 29/582 [02:22<40:47,  4.43s/it]

  [done]    Dominick Barlow — 399 shots

Fetching shot logs:   5%|█                    | 30/582 [02:27<43:00,  4.67s/it]

  [done]    Harrison Barnes — 575 shots

Fetching shot logs:   5%|█                    | 31/582 [02:33<45:27,  4.95s/it]

  [done]    Scottie Barnes — 1,123 shots

Fetching shot logs:   5%|█▏                   | 32/582 [02:38<45:51,  5.00s/it]

  [done]    Brooks Barnhizer — 71 shots

Fetching shot logs:   6%|█▏                   | 33/582 [02:43<45:28,  4.97s/it]

  [done]    RJ Barrett — 816 shots

Fetching shot logs:   6%|█▏                   | 34/582 [02:48<45:07,  4.94s/it]

  [done]    Charles Bassey — 47 shots

Fetching shot logs:   6%|█▎                   | 35/582 [02:53<45:51,  5.03s/it]

  [done]    Jamison Battle — 145 shots

Fetching shot logs:   6%|█▎                   | 36/582 [02:57<43:33,  4.79s/it]

  [done]    Nicolas Batum — 238 shots

Fetching shot logs:   6%|█▎                   | 37/582 [03:02<43:48,  4.82s/it]

  [done]    Bradley Beal — 48 shots

Fetching shot logs:   7%|█▎                   | 38/582 [03:06<41:28,  4.57s/it]

  [done]    MarJon Beauchamp — 76 shots

Fetching shot logs:   7%|█▍                   | 39/582 [03:13<48:59,  5.41s/it]

  [done]    Joan Beringer — 98 shots

Fetching shot logs:   7%|█▍                   | 40/582 [03:17<43:31,  4.82s/it]

  [done]    Saddiq Bey — 967 shots

Fetching shot logs:   7%|█▍                   | 41/582 [03:22<45:35,  5.06s/it]

  [done]    Goga Bitadze — 225 shots

Fetching shot logs:   7%|█▌                   | 42/582 [03:28<48:21,  5.37s/it]

  [done]    Bismack Biyombo — 15 shots

Fetching shot logs:   7%|█▌                   | 43/582 [03:33<46:25,  5.17s/it]

  [done]    Anthony Black — 772 shots

Fetching shot logs:   8%|█▌                   | 44/582 [03:38<45:05,  5.03s/it]

  [done]    Leaky Black — 103 shots

Fetching shot logs:   8%|█▌                   | 45/582 [03:42<42:27,  4.74s/it]

  [done]    Buddy Boeheim — 6 shots

Fetching shot logs:   8%|█▋                   | 46/582 [03:47<42:40,  4.78s/it]

  [done]    Bogdan Bogdanović — 152 shots

Fetching shot logs:   8%|█▋                   | 47/582 [03:50<39:42,  4.45s/it]

  [done]    Adem Bona — 220 shots

Fetching shot logs:   8%|█▋                   | 48/582 [03:57<43:54,  4.93s/it]

  [done]    Devin Booker — 1,198 shots

Fetching shot logs:   8%|█▊                   | 49/582 [04:03<47:01,  5.29s/it]

  [done]    Chris Boucher — 25 shots

Fetching shot logs:   9%|█▊                   | 50/582 [04:08<46:02,  5.19s/it]

  [done]    Jamaree Bouyea — 236 shots

Fetching shot logs:   9%|█▊                   | 51/582 [04:13<47:16,  5.34s/it]

  [done]    Tony Bradley — 117 shots

Fetching shot logs:   9%|█▉                   | 52/582 [04:18<46:03,  5.21s/it]

  [done]    Malaki Branham — 91 shots

Fetching shot logs:   9%|█▉                   | 53/582 [04:23<45:32,  5.16s/it]

  [done]    Christian Braun — 389 shots

Fetching shot logs:   9%|█▉                   | 54/582 [04:29<46:33,  5.29s/it]

  [done]    Koby Brea — 36 shots

Fetching shot logs:   9%|█▉                   | 55/582 [04:34<46:38,  5.31s/it]

  [done]    Mikal Bridges — 963 shots

Fetching shot logs:  10%|██                   | 56/582 [04:39<46:30,  5.30s/it]

  [done]    Miles Bridges — 1,042 shots

Fetching shot logs:  10%|██                   | 57/582 [04:43<42:50,  4.90s/it]

  [done]    Dillon Brooks — 959 shots

Fetching shot logs:  10%|██                   | 58/582 [04:47<40:28,  4.64s/it]

  [done]    Johni Broome — 24 shots

Fetching shot logs:  10%|██▏                  | 59/582 [04:53<41:47,  4.79s/it]

  [done]    Bruce Brown — 522 shots

Fetching shot logs:  10%|██▏                  | 60/582 [04:58<43:59,  5.06s/it]

  [done]    Darius Brown — 1 shots

Fetching shot logs:  10%|██▏                  | 61/582 [05:04<46:31,  5.36s/it]

  [done]    Jaylen Brown — 1,543 shots

Fetching shot logs:  11%|██▏                  | 62/582 [05:09<44:08,  5.09s/it]

  [done]    Kobe Brown — 271 shots

Fetching shot logs:  11%|██▎                  | 63/582 [05:15<46:37,  5.39s/it]

  [done]    Jalen Brunson — 1,475 shots

Fetching shot logs:  11%|██▎                  | 64/582 [05:20<44:45,  5.19s/it]

  [done]    Carter Bryant — 265 shots

Fetching shot logs:  11%|██▎                  | 65/582 [05:24<43:32,  5.05s/it]

  [done]    Thomas Bryant — 267 shots

Fetching shot logs:  11%|██▍                  | 66/582 [05:29<41:15,  4.80s/it]

  [done]    Kobe Bufkin — 50 shots

Fetching shot logs:  12%|██▍                  | 67/582 [05:33<41:32,  4.84s/it]

  [done]    Tyler Burton — 112 shots

Fetching shot logs:  12%|██▍                  | 68/582 [05:38<40:30,  4.73s/it]

  [done]    Jimmy Butler III — 462 shots

Fetching shot logs:  12%|██▍                  | 69/582 [05:43<40:59,  4.79s/it]

  [done]    Matas Buzelis — 963 shots

Fetching shot logs:  12%|██▌                  | 70/582 [05:46<37:32,  4.40s/it]

  [done]    Jamal Cain — 152 shots

Fetching shot logs:  12%|██▌                  | 71/582 [05:52<40:26,  4.75s/it]

  [done]    Kentavious Caldwell-Pope — 366 shots

Fetching shot logs:  12%|██▌                  | 72/582 [05:56<38:55,  4.58s/it]

  [done]    Toumani Camara — 891 shots

Fetching shot logs:  13%|██▋                  | 73/582 [06:02<41:26,  4.89s/it]

  [done]    Clint Capela — 227 shots

Fetching shot logs:  13%|██▋                  | 74/582 [06:08<43:38,  5.15s/it]

  [done]    Dylan Cardwell — 179 shots

Fetching shot logs:  13%|██▋                  | 75/582 [06:13<44:53,  5.31s/it]

  [done]    Branden Carlson — 186 shots

Fetching shot logs:  13%|██▋                  | 76/582 [06:19<47:03,  5.58s/it]

  [done]    Bub Carrington — 741 shots

Fetching shot logs:  13%|██▊                  | 77/582 [06:24<43:16,  5.14s/it]

  [done]    Devin Carter — 292 shots

Fetching shot logs:  13%|██▊                  | 78/582 [06:28<42:05,  5.01s/it]

  [done]    Jevon Carter — 307 shots

Fetching shot logs:  14%|██▊                  | 79/582 [06:33<40:16,  4.80s/it]

  [done]    Wendell Carter Jr. — 637 shots

Fetching shot logs:  14%|██▉                  | 80/582 [06:37<40:06,  4.79s/it]

  [done]    Alex Caruso — 300 shots

Fetching shot logs:  14%|██▉                  | 81/582 [06:41<38:27,  4.61s/it]

  [done]    Stephon Castle — 817 shots

Fetching shot logs:  14%|██▉                  | 82/582 [06:47<39:33,  4.75s/it]

  [done]    Colin Castleton — 5 shots

Fetching shot logs:  14%|██▉                  | 83/582 [06:50<36:21,  4.37s/it]

  [done]    Julian Champagnie — 689 shots

Fetching shot logs:  14%|███                  | 84/582 [06:55<36:53,  4.44s/it]

  [done]    Justin Champagnie — 462 shots

Fetching shot logs:  15%|███                  | 85/582 [07:00<38:10,  4.61s/it]

  [done]    Kennedy Chandler — 137 shots

Fetching shot logs:  15%|███                  | 86/582 [07:07<44:58,  5.44s/it]

  [done]    Cam Christie — 139 shots

Fetching shot logs:  15%|███▏                 | 87/582 [07:12<42:37,  5.17s/it]

  [done]    Max Christie — 725 shots

Fetching shot logs:  15%|███▏                 | 88/582 [07:17<43:45,  5.31s/it]

  [done]    Moussa Cisse — 115 shots

Fetching shot logs:  15%|███▏                 | 89/582 [07:21<40:16,  4.90s/it]

  [done]    Sidy Cissoko — 334 shots

Fetching shot logs:  15%|███▏                 | 90/582 [07:25<38:26,  4.69s/it]

  [done]    Jaylen Clark — 228 shots

Fetching shot logs:  16%|███▎                 | 91/582 [07:31<40:24,  4.94s/it]

  [done]    Brandon Clarke — 9 shots

Fetching shot logs:  16%|███▎                 | 92/582 [07:35<39:21,  4.82s/it]

  [done]    Jordan Clarkson — 526 shots

Fetching shot logs:  16%|███▎                 | 93/582 [07:40<38:15,  4.69s/it]

  [done]    Nic Claxton — 583 shots

Fetching shot logs:  16%|███▍                 | 94/582 [07:45<40:12,  4.94s/it]

  [done]    Walter Clayton Jr. — 461 shots

Fetching shot logs:  16%|███▍                 | 95/582 [07:50<40:18,  4.97s/it]

  [done]    Nique Clifford — 596 shots

Fetching shot logs:  16%|███▍                 | 96/582 [07:55<40:03,  4.94s/it]

  [done]    Donovan Clingan — 684 shots

Fetching shot logs:  17%|███▌                 | 97/582 [08:00<39:43,  4.91s/it]

  [done]    Noah Clowney — 631 shots

Fetching shot logs:  17%|███▌                 | 98/582 [08:04<37:37,  4.66s/it]

  [done]    Amir Coffey — 113 shots

Fetching shot logs:  17%|███▌                 | 99/582 [08:10<39:39,  4.93s/it]

  [done]    Isaiah Collier — 515 shots

Fetching shot logs:  17%|███▍                | 100/582 [08:15<39:48,  4.95s/it]

  [done]    John Collins — 659 shots

Fetching shot logs:  17%|███▍                | 101/582 [08:20<39:35,  4.94s/it]

  [done]    Zach Collins — 64 shots

Fetching shot logs:  18%|███▌                | 102/582 [08:25<39:51,  4.98s/it]

  [done]    Mike Conley — 215 shots

Fetching shot logs:  18%|███▌                | 103/582 [08:30<40:40,  5.10s/it]

  [done]    Pat Connaughton — 85 shots

Fetching shot logs:  18%|███▌                | 104/582 [08:35<40:21,  5.07s/it]

  [done]    Javonte Cooke — 41 shots

Fetching shot logs:  18%|███▌                | 105/582 [08:41<43:22,  5.46s/it]

  [done]    Sharife Cooper — 247 shots

Fetching shot logs:  18%|███▋                | 106/582 [08:46<41:50,  5.27s/it]

  [done]    Bilal Coulibaly — 541 shots

Fetching shot logs:  18%|███▋                | 107/582 [08:52<42:27,  5.36s/it]

  [done]    Cedric Coward — 648 shots

Fetching shot logs:  19%|███▋                | 108/582 [08:57<40:52,  5.17s/it]

  [done]    Isaiah Crawford — 24 shots

Fetching shot logs:  19%|███▋                | 109/582 [09:01<38:59,  4.95s/it]

  [done]    LJ Cryer — 117 shots

Fetching shot logs:  19%|███▊                | 110/582 [09:07<42:00,  5.34s/it]

  [done]    Cade Cunningham — 1,189 shots

Fetching shot logs:  19%|███▊                | 111/582 [09:12<39:42,  5.06s/it]

  [done]    Seth Curry — 49 shots

Fetching shot logs:  19%|███▊                | 112/582 [09:16<37:55,  4.84s/it]

  [done]    Stephen Curry — 799 shots

Fetching shot logs:  19%|███▉                | 113/582 [09:20<36:36,  4.68s/it]

  [done]    Pacôme Dadiet — 48 shots

Fetching shot logs:  20%|███▉                | 114/582 [09:25<37:13,  4.77s/it]

  [done]    Dyson Daniels — 777 shots

Fetching shot logs:  20%|███▉                | 115/582 [09:29<35:01,  4.50s/it]

  [done]    N'Faly Dante — 4 shots

Fetching shot logs:  20%|███▉                | 116/582 [09:35<37:25,  4.82s/it]

  [done]    Anthony Davis — 334 shots

Fetching shot logs:  20%|████                | 117/582 [09:39<35:21,  4.56s/it]

  [done]    JD Davison — 64 shots

Fetching shot logs:  20%|████                | 118/582 [09:44<38:03,  4.92s/it]

  [done]    DeMar DeRozan — 1,005 shots

Fetching shot logs:  20%|████                | 119/582 [09:49<37:34,  4.87s/it]

  [done]    RayJ Dennis — 83 shots

Fetching shot logs:  21%|████                | 120/582 [09:54<36:59,  4.80s/it]

  [done]    Donte DiVincenzo — 835 shots

Fetching shot logs:  21%|████▏               | 121/582 [09:58<34:52,  4.54s/it]

  [done]    Moussa Diabaté — 363 shots

Fetching shot logs:  21%|████▏               | 122/582 [10:03<37:14,  4.86s/it]

  [done]    Mohamed Diawara — 213 shots

Fetching shot logs:  21%|████▏               | 123/582 [10:07<34:11,  4.47s/it]

  [done]    Gradey Dick — 384 shots

Fetching shot logs:  21%|████▎               | 124/582 [10:11<33:45,  4.42s/it]

  [done]    Hunter Dickinson — 14 shots

Fetching shot logs:  21%|████▎               | 125/582 [10:16<35:02,  4.60s/it]

  [done]    Ousmane Dieng — 398 shots

Fetching shot logs:  22%|████▎               | 126/582 [10:21<34:57,  4.60s/it]

  [done]    Rob Dillingham — 412 shots

Fetching shot logs:  22%|████▎               | 127/582 [10:26<35:07,  4.63s/it]

  [done]    Luka Dončić — 1,457 shots

Fetching shot logs:  22%|████▍               | 128/582 [10:32<38:04,  5.03s/it]

  [done]    Luguentz Dort — 524 shots

Fetching shot logs:  22%|████▍               | 129/582 [10:36<36:48,  4.88s/it]

  [done]    Ayo Dosunmu — 747 shots

Fetching shot logs:  22%|████▍               | 130/582 [10:41<36:57,  4.91s/it]

  [done]    Andre Drummond — 337 shots

Fetching shot logs:  23%|████▌               | 131/582 [10:47<38:38,  5.14s/it]

  [done]    Kris Dunn — 477 shots

Fetching shot logs:  23%|████▌               | 132/582 [10:52<38:17,  5.11s/it]

  [done]    Ryan Dunn — 362 shots

Fetching shot logs:  23%|████▌               | 133/582 [10:55<34:39,  4.63s/it]

  [done]    Kevin Durant — 1,376 shots

Fetching shot logs:  23%|████▌               | 134/582 [11:00<35:41,  4.78s/it]

  [done]    Jalen Duren — 803 shots

Fetching shot logs:  23%|████▋               | 135/582 [11:06<37:39,  5.05s/it]

  [done]    Egor Dëmin — 449 shots

Fetching shot logs:  23%|████▋               | 136/582 [11:12<39:25,  5.30s/it]

  [done]    Tari Eason — 580 shots

Fetching shot logs:  24%|████▋               | 137/582 [11:18<40:06,  5.41s/it]

  [done]    Zach Edey — 98 shots

Fetching shot logs:  24%|████▋               | 138/582 [11:22<37:29,  5.07s/it]

  [done]    VJ Edgecombe — 1,030 shots

Fetching shot logs:  24%|████▊               | 139/582 [11:27<38:32,  5.22s/it]

  [done]    Anthony Edwards — 1,231 shots

Fetching shot logs:  24%|████▊               | 140/582 [11:32<37:42,  5.12s/it]

  [done]    Justin Edwards — 320 shots

Fetching shot logs:  24%|████▊               | 141/582 [11:37<35:51,  4.88s/it]

  [done]    Keon Ellis — 384 shots

Fetching shot logs:  24%|████▉               | 142/582 [11:41<34:17,  4.68s/it]

  [done]    Joel Embiid — 697 shots

Fetching shot logs:  25%|████▉               | 143/582 [11:45<32:51,  4.49s/it]

  [done]    Tristan Enaruna — 28 shots

Fetching shot logs:  25%|████▉               | 144/582 [11:49<32:07,  4.40s/it]

  [done]    Noa Essengue — 3 shots

Fetching shot logs:  25%|████▉               | 145/582 [11:54<33:32,  4.61s/it]

  [done]    Tyson Etienne — 145 shots

Fetching shot logs:  25%|█████               | 146/582 [12:00<35:10,  4.84s/it]

  [done]    Drew Eubanks — 156 shots

Fetching shot logs:  25%|█████               | 147/582 [12:04<34:22,  4.74s/it]

  [done]    Tosan Evbuomwan — 1 shots

Fetching shot logs:  25%|█████               | 148/582 [12:10<36:07,  4.99s/it]

  [done]    Jeremiah Fears — 1,006 shots

Fetching shot logs:  26%|█████               | 149/582 [12:15<36:52,  5.11s/it]

  [done]    Kyle Filipowski — 657 shots

Fetching shot logs:  26%|█████▏              | 150/582 [12:20<36:04,  5.01s/it]

  [done]    Dorian Finney-Smith — 132 shots

Fetching shot logs:  26%|█████▏              | 151/582 [12:25<36:34,  5.09s/it]

  [done]    Cooper Flagg — 1,194 shots

Fetching shot logs:  26%|█████▏              | 152/582 [12:30<34:55,  4.87s/it]

  [done]    Rasheer Fleming — 215 shots

Fetching shot logs:  26%|█████▎              | 153/582 [12:36<37:31,  5.25s/it]

  [done]    Trentyn Flowers — 3 shots

Fetching shot logs:  26%|█████▎              | 154/582 [12:39<33:24,  4.68s/it]

  [done]    Simone Fontecchio — 471 shots

Fetching shot logs:  27%|█████▎              | 155/582 [12:42<30:35,  4.30s/it]

  [done]    De'Aaron Fox — 1,047 shots

Fetching shot logs:  27%|█████▎              | 156/582 [12:47<31:04,  4.38s/it]

  [done]    Enrique Freeman — 8 shots

Fetching shot logs:  27%|█████▍              | 157/582 [12:51<30:39,  4.33s/it]

  [done]    Markelle Fultz — 11 shots

Fetching shot logs:  27%|█████▍              | 158/582 [12:57<33:11,  4.70s/it]

  [done]    Johnny Furphy — 149 shots

Fetching shot logs:  27%|█████▍              | 159/582 [13:02<35:07,  4.98s/it]

  [done]    Daniel Gafford — 316 shots

Fetching shot logs:  27%|█████▍              | 160/582 [13:07<34:02,  4.84s/it]

  [done]    Andersson Garcia — 29 shots

Fetching shot logs:  28%|█████▌              | 161/582 [13:12<33:55,  4.84s/it]

  [done]    Myron Gardner — 123 shots

Fetching shot logs:  28%|█████▌              | 162/582 [13:17<34:17,  4.90s/it]

  [done]    Darius Garland — 672 shots

Fetching shot logs:  28%|█████▌              | 163/582 [13:21<33:48,  4.84s/it]

  [done]    Luka Garza — 357 shots

Fetching shot logs:  28%|█████▋              | 164/582 [13:25<30:38,  4.40s/it]

  [done]    Keyonte George — 881 shots

Fetching shot logs:  28%|█████▋              | 165/582 [13:30<31:24,  4.52s/it]

  [done]    Kyshawn George — 577 shots

Fetching shot logs:  29%|█████▋              | 166/582 [13:34<30:53,  4.46s/it]

  [done]    Paul George — 513 shots

Fetching shot logs:  29%|█████▋              | 167/582 [13:40<33:10,  4.80s/it]

  [done]    Taj Gibson — 26 shots

Fetching shot logs:  29%|█████▊              | 168/582 [13:44<31:47,  4.61s/it]

  [done]    Josh Giddey — 717 shots

Fetching shot logs:  29%|█████▊              | 169/582 [13:48<31:25,  4.56s/it]

  [done]    Keshon Gilbert — 12 shots

Fetching shot logs:  29%|█████▊              | 170/582 [13:53<31:32,  4.59s/it]

  [done]    Shai Gilgeous-Alexander — 1,321 shots

Fetching shot logs:  29%|█████▉              | 171/582 [13:58<32:51,  4.80s/it]

  [done]    Anthony Gill — 215 shots

Fetching shot logs:  30%|█████▉              | 172/582 [14:02<30:23,  4.45s/it]

  [done]    Collin Gillespie — 842 shots

Fetching shot logs:  30%|█████▉              | 173/582 [14:06<30:12,  4.43s/it]

  [done]    Rudy Gobert — 491 shots

Fetching shot logs:  30%|█████▉              | 174/582 [14:11<30:48,  4.53s/it]

  [done]    Vladislav Goldin — 4 shots

Fetching shot logs:  30%|██████              | 175/582 [14:17<33:11,  4.89s/it]

  [done]    Hugo González — 246 shots

Fetching shot logs:  30%|██████              | 176/582 [14:21<31:50,  4.70s/it]

  [done]    Jordan Goodwin — 555 shots

Fetching shot logs:  30%|██████              | 177/582 [14:27<34:04,  5.05s/it]

  [done]    Aaron Gordon — 398 shots

Fetching shot logs:  31%|██████              | 178/582 [14:30<31:00,  4.61s/it]

  [done]    Eric Gordon — 21 shots

Fetching shot logs:  31%|██████▏             | 179/582 [14:36<32:15,  4.80s/it]

  [done]    Jerami Grant — 730 shots

Fetching shot logs:  31%|██████▏             | 180/582 [14:41<32:33,  4.86s/it]

  [done]    Hayden Gray — 3 shots

Fetching shot logs:  31%|██████▏             | 181/582 [14:44<30:27,  4.56s/it]

  [done]    AJ Green — 618 shots

Fetching shot logs:  31%|██████▎             | 182/582 [14:51<33:43,  5.06s/it]

  [done]    Draymond Green — 491 shots

Fetching shot logs:  31%|██████▎             | 183/582 [14:56<33:18,  5.01s/it]

  [done]    Jalen Green — 512 shots

Fetching shot logs:  32%|██████▎             | 184/582 [15:00<31:31,  4.75s/it]

  [done]    Javonte Green — 414 shots

Fetching shot logs:  32%|██████▎             | 185/582 [15:06<34:26,  5.20s/it]

  [done]    Jeff Green — 68 shots

Fetching shot logs:  32%|██████▍             | 186/582 [15:11<33:13,  5.03s/it]

  [done]    Josh Green — 181 shots

Fetching shot logs:  32%|██████▍             | 187/582 [15:15<31:26,  4.77s/it]

  [done]    Quentin Grimes — 755 shots

Fetching shot logs:  32%|██████▍             | 188/582 [15:18<29:08,  4.44s/it]

  [done]    Mouhamadou Gueye — 11 shots

Fetching shot logs:  32%|██████▍             | 189/582 [15:23<28:42,  4.38s/it]

  [done]    Mouhamed Gueye — 290 shots

Fetching shot logs:  33%|██████▌             | 190/582 [15:27<29:27,  4.51s/it]

  [done]    Rui Hachimura — 597 shots

Fetching shot logs:  33%|██████▌             | 191/582 [15:33<30:54,  4.74s/it]

  [done]    PJ Hall — 59 shots

Fetching shot logs:  33%|██████▌             | 192/582 [15:41<37:38,  5.79s/it]

  [done]    Tim Hardaway Jr. — 779 shots

Fetching shot logs:  33%|██████▋             | 193/582 [15:46<36:42,  5.66s/it]

  [done]    James Harden — 1,123 shots

Fetching shot logs:  33%|██████▋             | 194/582 [15:52<36:19,  5.62s/it]

  [done]    Jaden Hardy — 429 shots

Fetching shot logs:  34%|██████▋             | 195/582 [15:58<36:32,  5.66s/it]

  [done]    Elijah Harkless — 161 shots

Fetching shot logs:  34%|██████▋             | 196/582 [16:03<35:08,  5.46s/it]

  [done]    Dylan Harper — 656 shots

Fetching shot logs:  34%|██████▊             | 197/582 [16:07<32:11,  5.02s/it]

  [done]    Ron Harper Jr. — 110 shots

Fetching shot logs:  34%|██████▊             | 198/582 [16:11<31:36,  4.94s/it]

  [done]    Gary Harris — 104 shots

Fetching shot logs:  34%|██████▊             | 199/582 [16:16<31:34,  4.95s/it]

  [done]    Tobias Harris — 659 shots

Fetching shot logs:  34%|██████▊             | 200/582 [16:22<32:22,  5.09s/it]

  [done]    Josh Hart — 592 shots

Fetching shot logs:  35%|██████▉             | 201/582 [16:26<31:38,  4.98s/it]

  [done]    Isaiah Hartenstein — 296 shots

Fetching shot logs:  35%|██████▉             | 202/582 [16:30<29:29,  4.66s/it]

  [done]    Sam Hauser — 601 shots

Fetching shot logs:  35%|██████▉             | 203/582 [16:34<27:09,  4.30s/it]

  [done]    Jordan Hawkins — 257 shots

Fetching shot logs:  35%|███████             | 204/582 [16:38<27:22,  4.35s/it]

  [done]    Jaxson Hayes — 262 shots

Fetching shot logs:  35%|███████             | 205/582 [16:44<29:45,  4.74s/it]

  [done]    Killian Hayes — 138 shots

Fetching shot logs:  35%|███████             | 206/582 [16:49<29:57,  4.78s/it]

  [done]    Nigel Hayes-Davis — 46 shots

Fetching shot logs:  36%|███████             | 207/582 [16:53<27:48,  4.45s/it]

  [done]    Scoot Henderson — 342 shots

Fetching shot logs:  36%|███████▏            | 208/582 [16:58<28:58,  4.65s/it]

  [done]    Taylor Hendricks — 355 shots

Fetching shot logs:  36%|███████▏            | 209/582 [17:05<33:09,  5.33s/it]

  [done]    Chucky Hepburn — 6 shots

Fetching shot logs:  36%|███████▏            | 210/582 [17:10<33:41,  5.43s/it]

  [done]    Tyler Herro — 515 shots

Fetching shot logs:  36%|███████▎            | 211/582 [17:15<32:14,  5.22s/it]

  [done]    Buddy Hield — 327 shots

Fetching shot logs:  36%|███████▎            | 212/582 [17:21<33:42,  5.47s/it]

  [done]    Haywood Highsmith — 23 shots

Fetching shot logs:  37%|███████▎            | 213/582 [17:26<32:49,  5.34s/it]

  [done]    Blake Hinson — 115 shots

Fetching shot logs:  37%|███████▎            | 214/582 [17:32<33:18,  5.43s/it]

  [done]    Aaron Holiday — 252 shots

Fetching shot logs:  37%|███████▍            | 215/582 [17:36<32:00,  5.23s/it]

  [done]    Jrue Holiday — 709 shots

Fetching shot logs:  37%|███████▍            | 216/582 [17:44<35:17,  5.78s/it]

  [done]    Ronald Holland II — 544 shots

Fetching shot logs:  37%|███████▍            | 217/582 [17:54<44:28,  7.31s/it]

  [done]    DaRon Holmes II — 61 shots

Fetching shot logs:  37%|███████▍            | 218/582 [18:03<47:12,  7.78s/it]

  [done]    Chet Holmgren — 779 shots

Fetching shot logs:  38%|███████▌            | 219/582 [18:08<42:02,  6.95s/it]

  [done]    Al Horford — 324 shots

Fetching shot logs:  38%|███████▌            | 220/582 [18:13<37:51,  6.28s/it]

  [done]    Caleb Houstan — 26 shots

Fetching shot logs:  38%|███████▌            | 221/582 [18:17<33:17,  5.53s/it]

  [done]    Jett Howard — 251 shots

Fetching shot logs:  38%|███████▋            | 222/582 [18:21<30:27,  5.08s/it]

  [done]    Kevin Huerter — 596 shots

Fetching shot logs:  38%|███████▋            | 223/582 [18:27<31:56,  5.34s/it]

  [done]    Jay Huff — 611 shots

Fetching shot logs:  38%|███████▋            | 224/582 [18:32<32:10,  5.39s/it]

  [done]    Ariel Hukporti — 80 shots

Fetching shot logs:  39%|███████▋            | 225/582 [18:38<32:27,  5.46s/it]

  [done]    De'Andre Hunter — 501 shots

Fetching shot logs:  39%|███████▊            | 226/582 [18:42<29:38,  5.00s/it]

  [done]    CJ Huntley — 11 shots

Fetching shot logs:  39%|███████▊            | 227/582 [18:47<30:49,  5.21s/it]

  [done]    Bones Hyland — 468 shots

Fetching shot logs:  39%|███████▊            | 228/582 [18:53<30:55,  5.24s/it]

  [done]    Oso Ighodaro — 366 shots

Fetching shot logs:  39%|███████▊            | 229/582 [18:57<28:26,  4.83s/it]

  [done]    Joe Ingles — 27 shots

Fetching shot logs:  40%|███████▉            | 230/582 [19:02<29:59,  5.11s/it]

  [done]    Brandon Ingram — 1,288 shots

Fetching shot logs:  40%|███████▉            | 231/582 [19:08<30:31,  5.22s/it]

  [done]    Harrison Ingram — 6 shots

Fetching shot logs:  40%|███████▉            | 232/582 [19:13<29:24,  5.04s/it]

  [done]    Jonathan Isaac — 109 shots

Fetching shot logs:  40%|████████            | 233/582 [19:18<30:30,  5.24s/it]

  [done]    Jaden Ivey — 256 shots

Fetching shot logs:  40%|████████            | 234/582 [19:23<29:15,  5.05s/it]

  [done]    GG Jackson — 514 shots

Fetching shot logs:  40%|████████            | 235/582 [19:28<30:08,  5.21s/it]

  [done]    Isaiah Jackson — 237 shots

Fetching shot logs:  41%|████████            | 236/582 [19:33<28:22,  4.92s/it]

  [done]    Quenton Jackson — 328 shots

Fetching shot logs:  41%|████████▏           | 237/582 [19:38<28:37,  4.98s/it]

  [done]    Andre Jackson Jr. — 119 shots

Fetching shot logs:  41%|████████▏           | 238/582 [19:42<27:53,  4.86s/it]

  [done]    Jaren Jackson Jr. — 719 shots

Fetching shot logs:  41%|████████▏           | 239/582 [19:47<27:18,  4.78s/it]

  [done]    Trayce Jackson-Davis — 124 shots

Fetching shot logs:  41%|████████▏           | 240/582 [19:52<27:36,  4.84s/it]

  [done]    Kasparas Jakučionis — 238 shots

Fetching shot logs:  41%|████████▎           | 241/582 [19:56<26:31,  4.67s/it]

  [done]    Bronny James — 115 shots

Fetching shot logs:  42%|████████▎           | 243/582 [20:05<25:22,  4.49s/it]

  [done]    Sion James — 372 shots

Fetching shot logs:  42%|████████▍           | 244/582 [20:09<25:16,  4.49s/it]

  [done]    Jaime Jaquez Jr. — 915 shots

Fetching shot logs:  42%|████████▍           | 245/582 [20:14<25:44,  4.58s/it]

  [done]    DeJon Jarreau — 83 shots

Fetching shot logs:  42%|████████▍           | 246/582 [20:20<27:13,  4.86s/it]

  [done]    DaQuan Jeffries — 19 shots

Fetching shot logs:  42%|████████▍           | 247/582 [20:24<26:14,  4.70s/it]

  [done]    Trey Jemison III — 10 shots

Fetching shot logs:  43%|████████▌           | 248/582 [20:29<26:04,  4.68s/it]

  [done]    Daniss Jenkins — 568 shots

Fetching shot logs:  43%|████████▌           | 249/582 [20:32<23:43,  4.27s/it]

  [done]    Ty Jerome — 215 shots

Fetching shot logs:  43%|████████▌           | 250/582 [20:38<26:19,  4.76s/it]

  [done]    Isaiah Joe — 543 shots

Fetching shot logs:  43%|████████▋           | 251/582 [20:42<25:15,  4.58s/it]

  [done]    AJ Johnson — 176 shots

Fetching shot logs:  43%|████████▋           | 252/582 [20:47<25:28,  4.63s/it]

  [done]    Cameron Johnson — 475 shots

Fetching shot logs:  43%|████████▋           | 253/582 [20:51<25:11,  4.59s/it]

  [done]    Chaney Johnson — 94 shots

Fetching shot logs:  44%|████████▋           | 254/582 [20:57<27:06,  4.96s/it]

  [done]    Jalen Johnson — 1,228 shots

Fetching shot logs:  44%|████████▊           | 255/582 [21:03<28:14,  5.18s/it]

  [done]    Keldon Johnson — 797 shots

Fetching shot logs:  44%|████████▊           | 256/582 [21:06<25:41,  4.73s/it]

  [done]    Keshad Johnson — 104 shots

Fetching shot logs:  44%|████████▊           | 257/582 [21:11<25:31,  4.71s/it]

  [done]    Tre Johnson — 647 shots

Fetching shot logs:  44%|████████▊           | 258/582 [21:17<26:44,  4.95s/it]

  [done]    Nikola Jokić — 1,132 shots

Fetching shot logs:  45%|████████▉           | 259/582 [21:20<23:43,  4.41s/it]

  [done]    Colby Jones — 3 shots

Fetching shot logs:  45%|████████▉           | 260/582 [21:25<25:07,  4.68s/it]

  [done]    Curtis Jones — 27 shots

Fetching shot logs:  45%|████████▉           | 261/582 [21:30<24:52,  4.65s/it]

  [done]    Dillon Jones — 9 shots

Fetching shot logs:  45%|█████████           | 262/582 [21:35<26:16,  4.93s/it]

  [done]    Herbert Jones — 478 shots

Fetching shot logs:  45%|█████████           | 263/582 [21:40<25:36,  4.82s/it]

  [done]    Isaac Jones — 7 shots

Fetching shot logs:  45%|█████████           | 264/582 [21:45<25:42,  4.85s/it]

  [done]    Kam Jones — 169 shots

Fetching shot logs:  46%|█████████           | 265/582 [21:50<26:58,  5.11s/it]

  [done]    Spencer Jones — 262 shots

Fetching shot logs:  46%|█████████▏          | 266/582 [21:55<25:55,  4.92s/it]

  [done]    Tre Jones — 617 shots

Fetching shot logs:  46%|█████████▏          | 267/582 [22:00<26:02,  4.96s/it]

  [done]    Tyus Jones — 218 shots

Fetching shot logs:  46%|█████████▏          | 268/582 [22:04<24:09,  4.62s/it]

  [done]    David Jones Garcia — 25 shots

Fetching shot logs:  46%|█████████▏          | 269/582 [22:08<23:21,  4.48s/it]

  [done]    Derrick Jones Jr. — 379 shots

Fetching shot logs:  46%|█████████▎          | 270/582 [22:12<22:59,  4.42s/it]

  [done]    DeAndre Jordan — 32 shots

Fetching shot logs:  47%|█████████▎          | 271/582 [22:18<24:31,  4.73s/it]

  [done]    Nikola Jović — 314 shots

Fetching shot logs:  47%|█████████▎          | 272/582 [22:22<24:26,  4.73s/it]

  [done]    Johnny Juzang — 38 shots

Fetching shot logs:  47%|█████████▍          | 273/582 [22:28<25:43,  5.00s/it]

  [done]    Ryan Kalkbrenner — 291 shots

Fetching shot logs:  47%|█████████▍          | 274/582 [22:32<24:03,  4.69s/it]

  [done]    Yuki Kawamura — 52 shots

Fetching shot logs:  47%|█████████▍          | 275/582 [22:36<22:59,  4.49s/it]

  [done]    Trevor Keels — 12 shots

Fetching shot logs:  47%|█████████▍          | 276/582 [22:43<25:57,  5.09s/it]

  [done]    Miles Kelly — 44 shots

Fetching shot logs:  48%|█████████▌          | 277/582 [22:47<25:23,  5.00s/it]

  [done]    Luke Kennard — 443 shots

Fetching shot logs:  48%|█████████▌          | 278/582 [22:52<24:59,  4.93s/it]

  [done]    Jayson Kent — 7 shots

Fetching shot logs:  48%|█████████▌          | 279/582 [22:57<24:26,  4.84s/it]

  [done]    Walker Kessler — 37 shots

Fetching shot logs:  48%|█████████▌          | 280/582 [23:01<24:10,  4.80s/it]

  [done]    Corey Kispert — 394 shots

Fetching shot logs:  48%|█████████▋          | 281/582 [23:06<24:11,  4.82s/it]

  [done]    Maxi Kleber — 73 shots

Fetching shot logs:  48%|█████████▋          | 282/582 [23:11<24:28,  4.89s/it]

  [done]    Bobi Klintman — 27 shots

Fetching shot logs:  49%|█████████▋          | 283/582 [23:17<24:48,  4.98s/it]

  [done]    Dalton Knecht — 191 shots

Fetching shot logs:  49%|█████████▊          | 284/582 [23:22<25:50,  5.20s/it]

  [done]    Kon Knueppel — 1,084 shots

Fetching shot logs:  49%|█████████▊          | 285/582 [23:26<23:41,  4.79s/it]

  [done]    Tyler Kolek — 248 shots

Fetching shot logs:  49%|█████████▊          | 286/582 [23:31<23:31,  4.77s/it]

  [done]    Christian Koloko — 74 shots

Fetching shot logs:  49%|█████████▊          | 287/582 [23:36<23:32,  4.79s/it]

  [done]    John Konchar — 199 shots

Fetching shot logs:  49%|█████████▉          | 288/582 [23:40<22:34,  4.61s/it]

  [done]    Luke Kornet — 272 shots

Fetching shot logs:  50%|█████████▉          | 289/582 [23:45<22:48,  4.67s/it]

  [done]    Vít Krejčí — 429 shots

Fetching shot logs:  50%|█████████▉          | 290/582 [23:48<20:55,  4.30s/it]

  [done]    Jonathan Kuminga — 339 shots

Fetching shot logs:  50%|██████████          | 291/582 [23:51<19:15,  3.97s/it]

  [done]    Kyle Kuzma — 689 shots

Fetching shot logs:  50%|██████████          | 292/582 [23:56<19:57,  4.13s/it]

  [done]    Jake LaRavia — 523 shots

Fetching shot logs:  50%|██████████          | 293/582 [24:00<19:55,  4.14s/it]

  [done]    Zach LaVine — 547 shots

Fetching shot logs:  51%|██████████          | 294/582 [24:04<19:10,  4.00s/it]

  [done]    Skal Labissiere — 10 shots

Fetching shot logs:  51%|██████████▏         | 295/582 [24:08<19:32,  4.08s/it]

  [done]    Jock Landale — 548 shots

Fetching shot logs:  51%|██████████▏         | 296/582 [24:12<19:39,  4.12s/it]

  [done]    Chaz Lanier — 89 shots

Fetching shot logs:  51%|██████████▏         | 297/582 [24:18<21:47,  4.59s/it]

  [done]    Pelle Larsson — 559 shots

Fetching shot logs:  51%|██████████▏         | 298/582 [24:22<21:08,  4.46s/it]

  [done]    A.J. Lawson — 78 shots

Fetching shot logs:  51%|██████████▎         | 299/582 [24:26<19:58,  4.23s/it]

  [done]    Caris LeVert — 391 shots

Fetching shot logs:  52%|██████████▎         | 300/582 [24:29<18:51,  4.01s/it]

  [done]    Kawhi Leonard — 1,258 shots

Fetching shot logs:  52%|██████████▎         | 301/582 [24:34<20:06,  4.29s/it]

  [done]    Malevy Leons — 72 shots

Fetching shot logs:  52%|██████████▍         | 302/582 [24:38<19:33,  4.19s/it]

  [done]    E.J. Liddell — 111 shots

Fetching shot logs:  52%|██████████▍         | 303/582 [24:42<19:43,  4.24s/it]

  [done]    Dereck Lively II — 18 shots

Fetching shot logs:  52%|██████████▍         | 304/582 [24:46<19:12,  4.15s/it]

  [done]    Isaiah Livers — 64 shots

Fetching shot logs:  52%|██████████▍         | 305/582 [24:51<19:42,  4.27s/it]

  [done]    Chris Livingston — 7 shots

Fetching shot logs:  53%|██████████▌         | 306/582 [24:57<21:48,  4.74s/it]

  [done]    Kevon Looney — 60 shots

Fetching shot logs:  53%|██████████▌         | 307/582 [25:01<21:18,  4.65s/it]

  [done]    Brook Lopez — 542 shots

Fetching shot logs:  53%|██████████▌         | 308/582 [25:06<21:59,  4.82s/it]

  [done]    Caleb Love — 490 shots

Fetching shot logs:  53%|██████████▌         | 309/582 [25:13<24:25,  5.37s/it]

  [done]    Kevin Love — 199 shots

Fetching shot logs:  53%|██████████▋         | 310/582 [25:18<23:52,  5.27s/it]

  [done]    Lawson Lovering — 10 shots

Fetching shot logs:  53%|██████████▋         | 311/582 [25:22<21:23,  4.74s/it]

  [done]    Kyle Lowry — 25 shots

Fetching shot logs:  54%|██████████▋         | 312/582 [25:26<20:48,  4.62s/it]

  [done]    Khaman Maluach — 105 shots

Fetching shot logs:  54%|██████████▊         | 313/582 [25:30<19:37,  4.38s/it]

  [done]    Sandro Mamukelashvili — 631 shots

Fetching shot logs:  54%|██████████▊         | 314/582 [25:34<18:53,  4.23s/it]

  [done]    Terance Mann — 368 shots

Fetching shot logs:  54%|██████████▊         | 315/582 [25:38<19:20,  4.35s/it]

  [done]    Tre Mann — 303 shots

Fetching shot logs:  54%|██████████▊         | 316/582 [25:43<20:25,  4.61s/it]

  [done]    Lauri Markkanen — 805 shots

Fetching shot logs:  54%|██████████▉         | 317/582 [25:48<20:55,  4.74s/it]

  [done]    Naji Marshall — 821 shots

Fetching shot logs:  55%|██████████▉         | 318/582 [25:54<22:11,  5.04s/it]

  [done]    Alijah Martin — 50 shots

Fetching shot logs:  55%|██████████▉         | 319/582 [25:59<22:07,  5.05s/it]

  [done]    Caleb Martin — 189 shots

Fetching shot logs:  55%|██████████▉         | 320/582 [26:03<20:37,  4.72s/it]

  [done]    Cody Martin — 10 shots

Fetching shot logs:  55%|███████████         | 321/582 [26:08<20:34,  4.73s/it]

  [done]    Tyrese Martin — 277 shots

Fetching shot logs:  55%|███████████         | 322/582 [26:12<19:07,  4.42s/it]

  [done]    Jahmai Mashack — 195 shots

Fetching shot logs:  55%|███████████         | 323/582 [26:17<20:51,  4.83s/it]

  [done]    Garrison Mathews — 52 shots

Fetching shot logs:  56%|███████████▏        | 324/582 [26:22<20:10,  4.69s/it]

  [done]    Bennedict Mathurin — 677 shots

Fetching shot logs:  56%|███████████▏        | 325/582 [26:26<20:01,  4.68s/it]

  [done]    Karlo Matković — 235 shots

Fetching shot logs:  56%|███████████▏        | 326/582 [26:31<19:09,  4.49s/it]

  [done]    Tyrese Maxey — 1,501 shots

Fetching shot logs:  56%|███████████▏        | 327/582 [26:35<18:31,  4.36s/it]

  [done]    Chris Mañon — 6 shots

Fetching shot logs:  56%|███████████▎        | 328/582 [26:39<18:14,  4.31s/it]

  [done]    Bez Mbeng — 100 shots

Fetching shot logs:  57%|███████████▎        | 329/582 [26:42<16:51,  4.00s/it]

  [done]    Miles McBride — 404 shots

Fetching shot logs:  57%|███████████▎        | 330/582 [26:46<16:14,  3.87s/it]

  [done]    Jared McCain — 480 shots

Fetching shot logs:  57%|███████████▎        | 331/582 [26:50<17:15,  4.13s/it]

  [done]    Mac McClung — 59 shots

Fetching shot logs:  57%|███████████▍        | 332/582 [26:56<19:39,  4.72s/it]

  [done]    CJ McCollum — 1,154 shots

Fetching shot logs:  57%|███████████▍        | 333/582 [27:01<19:16,  4.64s/it]

  [done]    T.J. McConnell — 450 shots

Fetching shot logs:  57%|███████████▍        | 334/582 [27:05<18:09,  4.39s/it]

  [done]    Kevin McCullar Jr. — 47 shots

Fetching shot logs:  58%|███████████▌        | 335/582 [27:11<20:20,  4.94s/it]

  [done]    Jaden McDaniels — 809 shots

Fetching shot logs:  58%|███████████▌        | 336/582 [27:15<18:36,  4.54s/it]

  [done]    Doug McDermott — 139 shots

Fetching shot logs:  58%|███████████▌        | 337/582 [27:18<17:00,  4.16s/it]

  [done]    Bryce McGowens — 237 shots

Fetching shot logs:  58%|███████████▌        | 338/582 [27:22<16:39,  4.10s/it]

  [done]    Jordan McLaughlin — 79 shots

Fetching shot logs:  58%|███████████▋        | 339/582 [27:27<17:37,  4.35s/it]

  [done]    Liam McNeeley — 95 shots

Fetching shot logs:  58%|███████████▋        | 340/582 [27:30<16:45,  4.16s/it]

  [done]    De'Anthony Melton — 528 shots

Fetching shot logs:  59%|███████████▋        | 341/582 [27:35<17:30,  4.36s/it]

  [done]    Sam Merrill — 484 shots

Fetching shot logs:  59%|███████████▊        | 342/582 [27:39<16:18,  4.08s/it]

  [done]    Khris Middleton — 540 shots

Fetching shot logs:  59%|███████████▊        | 343/582 [27:43<16:38,  4.18s/it]

  [done]    Brandon Miller — 1,044 shots

Fetching shot logs:  59%|███████████▊        | 344/582 [27:47<16:27,  4.15s/it]

  [done]    Emanuel Miller — 13 shots

Fetching shot logs:  59%|███████████▊        | 345/582 [27:51<15:33,  3.94s/it]

  [done]    Jordan Miller — 399 shots

Fetching shot logs:  59%|███████████▉        | 346/582 [27:56<17:06,  4.35s/it]

  [done]    Leonard Miller — 262 shots

Fetching shot logs:  60%|███████████▉        | 347/582 [28:00<16:29,  4.21s/it]

  [done]    Riley Minix — 23 shots

Fetching shot logs:  60%|███████████▉        | 348/582 [28:05<17:10,  4.40s/it]

  [done]    Josh Minott — 252 shots

Fetching shot logs:  60%|███████████▉        | 349/582 [28:09<16:37,  4.28s/it]

  [done]    Yves Missi — 294 shots

Fetching shot logs:  60%|████████████        | 350/582 [28:14<17:18,  4.48s/it]

  [done]    Ajay Mitchell — 590 shots

Fetching shot logs:  60%|████████████        | 351/582 [28:17<16:09,  4.20s/it]

  [done]    Davion Mitchell — 533 shots

Fetching shot logs:  60%|████████████        | 352/582 [28:22<16:58,  4.43s/it]

  [done]    Donovan Mitchell — 1,403 shots

Fetching shot logs:  61%|████████████▏       | 353/582 [28:27<17:49,  4.67s/it]

  [done]    Evan Mobley — 859 shots

Fetching shot logs:  61%|████████████▏       | 354/582 [28:31<16:42,  4.40s/it]

  [done]    Jonathan Mogbo — 44 shots

Fetching shot logs:  61%|████████████▏       | 355/582 [28:36<17:28,  4.62s/it]

  [done]    Malik Monk — 632 shots

Fetching shot logs:  61%|████████████▏       | 356/582 [28:41<17:51,  4.74s/it]

  [done]    Moses Moody — 557 shots

Fetching shot logs:  61%|████████████▎       | 357/582 [28:46<18:08,  4.84s/it]

  [done]    Wendell Moore Jr. — 7 shots

Fetching shot logs:  62%|████████████▎       | 358/582 [28:51<17:18,  4.64s/it]

  [done]    Alex Morales — 7 shots

Fetching shot logs:  62%|████████████▎       | 359/582 [28:55<16:38,  4.48s/it]

  [done]    Ja Morant — 322 shots

Fetching shot logs:  62%|████████████▎       | 360/582 [29:00<17:10,  4.64s/it]

  [done]    Monte Morris — 20 shots

Fetching shot logs:  62%|████████████▍       | 361/582 [29:04<16:42,  4.53s/it]

  [done]    Trey Murphy III — 1,050 shots

Fetching shot logs:  62%|████████████▍       | 362/582 [29:08<16:22,  4.47s/it]

  [done]    Dejounte Murray — 182 shots

Fetching shot logs:  62%|████████████▍       | 363/582 [29:12<16:02,  4.39s/it]

  [done]    Jamal Murray — 1,360 shots

Fetching shot logs:  63%|████████████▌       | 364/582 [29:17<16:02,  4.41s/it]

  [done]    Keegan Murray — 300 shots

Fetching shot logs:  63%|████████████▌       | 365/582 [29:21<15:50,  4.38s/it]

  [done]    Kris Murray — 276 shots

Fetching shot logs:  63%|████████████▌       | 366/582 [29:26<15:43,  4.37s/it]

  [done]    Collin Murray-Boyles — 342 shots

Fetching shot logs:  63%|████████████▌       | 367/582 [29:30<16:00,  4.47s/it]

  [done]    Svi Mykhailiuk — 362 shots

Fetching shot logs:  63%|████████████▋       | 368/582 [29:35<15:51,  4.45s/it]

  [done]    Pete Nance — 194 shots

Fetching shot logs:  63%|████████████▋       | 369/582 [29:38<14:26,  4.07s/it]

  [done]    Larry Nance Jr. — 124 shots

Fetching shot logs:  64%|████████████▋       | 370/582 [29:44<16:14,  4.59s/it]

  [done]    Grant Nelson — 9 shots

Fetching shot logs:  64%|████████████▋       | 371/582 [29:48<15:38,  4.45s/it]

  [done]    Andrew Nembhard — 753 shots

Fetching shot logs:  64%|████████████▊       | 372/582 [29:52<15:31,  4.44s/it]

  [done]    Ryan Nembhard — 390 shots

Fetching shot logs:  64%|████████████▊       | 373/582 [29:57<15:57,  4.58s/it]

  [done]    Aaron Nesmith — 512 shots

Fetching shot logs:  64%|████████████▊       | 374/582 [30:02<16:05,  4.64s/it]

  [done]    Asa Newell — 169 shots

Fetching shot logs:  64%|████████████▉       | 375/582 [30:06<15:39,  4.54s/it]

  [done]    Tristen Newton — 9 shots

Fetching shot logs:  65%|████████████▉       | 376/582 [30:12<16:55,  4.93s/it]

  [done]    Yanic Konan Niederhäuser — 100 shots

Fetching shot logs:  65%|████████████▉       | 377/582 [30:17<16:48,  4.92s/it]

  [done]    Zeke Nnaji — 151 shots

Fetching shot logs:  65%|████████████▉       | 378/582 [30:22<17:17,  5.08s/it]

  [done]    Jusuf Nurkić — 358 shots

Fetching shot logs:  65%|█████████████       | 379/582 [30:28<17:29,  5.17s/it]

  [done]    Royce O'Neale — 625 shots

Fetching shot logs:  65%|█████████████       | 380/582 [30:32<16:35,  4.93s/it]

  [done]    Josh Oduro — 17 shots

Fetching shot logs:  65%|█████████████       | 381/582 [30:36<15:29,  4.62s/it]

  [done]    Toby Okani — 70 shots

Fetching shot logs:  66%|█████████████▏      | 382/582 [30:41<15:22,  4.61s/it]

  [done]    Josh Okogie — 294 shots

Fetching shot logs:  66%|█████████████▏      | 383/582 [30:48<17:47,  5.37s/it]

  [done]    Onyeka Okongwu — 860 shots

Fetching shot logs:  66%|█████████████▏      | 384/582 [30:51<15:48,  4.79s/it]

  [done]    Isaac Okoro — 459 shots

Fetching shot logs:  66%|█████████████▏      | 385/582 [30:56<15:34,  4.74s/it]

  [done]    Lachlan Olbrich — 77 shots

Fetching shot logs:  66%|█████████████▎      | 386/582 [30:59<14:26,  4.42s/it]

  [done]    Kelly Olynyk — 96 shots

Fetching shot logs:  66%|█████████████▎      | 387/582 [31:05<15:09,  4.66s/it]

  [done]    Norchad Omier — 10 shots

Fetching shot logs:  67%|█████████████▎      | 388/582 [31:08<14:01,  4.34s/it]

  [done]    Kelly Oubre Jr. — 544 shots

Fetching shot logs:  67%|█████████████▎      | 389/582 [31:12<13:25,  4.17s/it]

  [done]    Chris Paul — 56 shots

Fetching shot logs:  67%|█████████████▍      | 390/582 [31:17<13:51,  4.33s/it]

  [done]    Cameron Payne — 149 shots

Fetching shot logs:  67%|█████████████▍      | 391/582 [31:20<12:55,  4.06s/it]

  [done]    Gary Payton II — 415 shots

Fetching shot logs:  67%|█████████████▍      | 392/582 [31:24<13:00,  4.11s/it]

  [done]    Micah Peavy — 275 shots

Fetching shot logs:  68%|█████████████▌      | 393/582 [31:30<13:53,  4.41s/it]

  [done]    Sean Pedulla — 15 shots

Fetching shot logs:  68%|█████████████▌      | 394/582 [31:35<14:39,  4.68s/it]

  [done]    Noah Penda — 203 shots

Fetching shot logs:  68%|█████████████▌      | 395/582 [31:40<14:53,  4.78s/it]

  [done]    Taelon Peter — 158 shots

Fetching shot logs:  68%|█████████████▌      | 396/582 [31:44<14:23,  4.64s/it]

  [done]    Drew Peterson — 16 shots

Fetching shot logs:  68%|█████████████▋      | 397/582 [31:49<14:09,  4.59s/it]

  [done]    Julian Phillips — 121 shots

Fetching shot logs:  68%|█████████████▋      | 398/582 [31:52<13:06,  4.27s/it]

  [done]    Jalen Pickett — 232 shots

Fetching shot logs:  69%|█████████████▋      | 399/582 [31:56<12:42,  4.17s/it]

  [done]    Scotty Pippen Jr. — 96 shots

Fetching shot logs:  69%|█████████████▋      | 400/582 [32:00<12:41,  4.18s/it]

  [done]    Daeqwon Plowden — 279 shots

Fetching shot logs:  69%|█████████████▊      | 401/582 [32:03<11:41,  3.88s/it]

  [done]    Mason Plumlee — 14 shots

Fetching shot logs:  69%|█████████████▊      | 402/582 [32:07<11:27,  3.82s/it]

  [done]    Brandin Podziemski — 866 shots

Fetching shot logs:  69%|█████████████▊      | 403/582 [32:12<11:53,  3.98s/it]

  [done]    Jakob Poeltl — 310 shots

Fetching shot logs:  69%|█████████████▉      | 404/582 [32:16<12:28,  4.21s/it]

  [done]    Jordan Poole — 444 shots

Fetching shot logs:  70%|█████████████▉      | 405/582 [32:21<12:25,  4.21s/it]

  [done]    Craig Porter Jr. — 258 shots

Fetching shot logs:  70%|█████████████▉      | 406/582 [32:24<11:51,  4.04s/it]

  [done]    Kevin Porter Jr. — 514 shots

Fetching shot logs:  70%|█████████████▉      | 407/582 [32:28<11:22,  3.90s/it]

  [done]    Michael Porter Jr. — 958 shots

Fetching shot logs:  70%|██████████████      | 408/582 [32:33<12:46,  4.41s/it]

  [done]    Bobby Portis — 750 shots

Fetching shot logs:  70%|██████████████      | 409/582 [32:38<13:22,  4.64s/it]

  [done]    Kristaps Porziņģis — 388 shots

Fetching shot logs:  70%|██████████████      | 410/582 [32:43<13:04,  4.56s/it]

  [done]    Quinten Post — 439 shots

Fetching shot logs:  71%|██████████████      | 411/582 [32:48<13:31,  4.74s/it]

  [done]    Micah Potter — 293 shots

Fetching shot logs:  71%|██████████████▏     | 412/582 [32:56<16:26,  5.80s/it]

  [done]    John Poulakidas — 91 shots

Fetching shot logs:  71%|██████████████▏     | 413/582 [33:02<16:08,  5.73s/it]

  [done]    Drake Powell — 358 shots

Fetching shot logs:  71%|██████████████▏     | 414/582 [33:05<13:57,  4.98s/it]

  [done]    Dwight Powell — 101 shots

Fetching shot logs:  71%|██████████████▎     | 415/582 [33:10<13:59,  5.03s/it]

  [done]    Norman Powell — 895 shots

Fetching shot logs:  71%|██████████████▎     | 416/582 [33:15<14:02,  5.07s/it]

  [done]    Taurean Prince — 191 shots

Fetching shot logs:  72%|██████████████▎     | 417/582 [33:20<13:54,  5.06s/it]

  [done]    Payton Pritchard — 1,091 shots

Fetching shot logs:  72%|██████████████▎     | 418/582 [33:26<14:07,  5.17s/it]

  [done]    Tyrese Proctor — 225 shots

Fetching shot logs:  72%|██████████████▍     | 419/582 [33:31<13:41,  5.04s/it]

  [done]    Olivier-Maxence Prosper — 350 shots

Fetching shot logs:  72%|██████████████▍     | 420/582 [33:36<14:00,  5.19s/it]

  [done]    Zyon Pullin — 13 shots

Fetching shot logs:  72%|██████████████▍     | 421/582 [33:41<13:33,  5.05s/it]

  [done]    Derik Queen — 748 shots

Fetching shot logs:  73%|██████████████▌     | 422/582 [33:45<13:05,  4.91s/it]

  [done]    Neemias Queta — 499 shots

Fetching shot logs:  73%|██████████████▌     | 423/582 [33:50<12:33,  4.74s/it]

  [done]    Immanuel Quickley — 905 shots

Fetching shot logs:  73%|██████████████▌     | 424/582 [33:55<12:45,  4.85s/it]

  [done]    Julius Randle — 1,207 shots

Fetching shot logs:  73%|██████████████▌     | 425/582 [33:59<12:27,  4.76s/it]

  [done]    Maxime Raynaud — 671 shots

Fetching shot logs:  73%|██████████████▋     | 426/582 [34:04<12:16,  4.72s/it]

  [done]    Duop Reath — 74 shots

Fetching shot logs:  73%|██████████████▋     | 427/582 [34:09<12:10,  4.71s/it]

  [done]    Austin Reaves — 762 shots

Fetching shot logs:  74%|██████████████▋     | 428/582 [34:13<11:41,  4.56s/it]

  [done]    Paul Reed — 339 shots

Fetching shot logs:  74%|██████████████▋     | 429/582 [34:18<11:40,  4.58s/it]

  [done]    Julian Reese — 119 shots

Fetching shot logs:  74%|██████████████▊     | 430/582 [34:23<12:04,  4.77s/it]

  [done]    Antonio Reeves — 20 shots

Fetching shot logs:  74%|██████████████▊     | 431/582 [34:28<12:07,  4.82s/it]

  [done]    Naz Reid — 871 shots

Fetching shot logs:  74%|██████████████▊     | 432/582 [34:32<11:25,  4.57s/it]

  [done]    Will Richard — 346 shots

Fetching shot logs:  74%|██████████████▉     | 433/582 [34:37<11:35,  4.67s/it]

  [done]    Nick Richards — 201 shots

Fetching shot logs:  75%|██████████████▉     | 434/582 [34:41<11:01,  4.47s/it]

  [done]    Jase Richardson — 188 shots

Fetching shot logs:  75%|██████████████▉     | 435/582 [34:46<11:31,  4.70s/it]

  [done]    Kadary Richmond — 16 shots

Fetching shot logs:  75%|██████████████▉     | 436/582 [34:52<12:17,  5.05s/it]

  [done]    Will Riley — 618 shots

Fetching shot logs:  75%|███████████████     | 437/582 [34:55<11:15,  4.66s/it]

  [done]    Zaccharie Risacher — 536 shots

Fetching shot logs:  75%|███████████████     | 438/582 [34:59<10:30,  4.38s/it]

  [done]    Duncan Robinson — 698 shots

Fetching shot logs:  75%|███████████████     | 439/582 [35:03<10:03,  4.22s/it]

  [done]    Mitchell Robinson — 206 shots

Fetching shot logs:  76%|███████████████     | 440/582 [35:07<09:46,  4.13s/it]

  [done]    Orlando Robinson — 5 shots

Fetching shot logs:  76%|███████████████▏    | 441/582 [35:11<09:48,  4.17s/it]

  [done]    Jeremiah Robinson-Earl — 100 shots

Fetching shot logs:  76%|███████████████▏    | 442/582 [35:15<09:19,  4.00s/it]

  [done]    David Roddy — 30 shots

Fetching shot logs:  76%|███████████████▏    | 443/582 [35:20<09:49,  4.24s/it]

  [done]    Ryan Rollins — 1,030 shots

Fetching shot logs:  76%|███████████████▎    | 444/582 [35:25<10:18,  4.48s/it]

  [done]    Rayan Rupert — 313 shots

Fetching shot logs:  76%|███████████████▎    | 445/582 [35:29<10:08,  4.44s/it]

  [done]    D'Angelo Russell — 232 shots

Fetching shot logs:  77%|███████████████▎    | 446/582 [35:34<10:26,  4.61s/it]

  [done]    Cormac Ryan — 102 shots

Fetching shot logs:  77%|███████████████▎    | 447/582 [35:38<09:52,  4.39s/it]

  [done]    Domantas Sabonis — 221 shots

Fetching shot logs:  77%|███████████████▍    | 448/582 [35:42<09:40,  4.33s/it]

  [done]    Tidjane Salaün — 159 shots

Fetching shot logs:  77%|███████████████▍    | 449/582 [35:46<09:25,  4.25s/it]

  [done]    Hunter Sallis — 5 shots

Fetching shot logs:  77%|███████████████▍    | 450/582 [35:51<09:56,  4.52s/it]

  [done]    Kobe Sanders — 384 shots

Fetching shot logs:  77%|███████████████▍    | 451/582 [35:56<10:12,  4.67s/it]

  [done]    Payton Sandfort — 26 shots

Fetching shot logs:  78%|███████████████▌    | 452/582 [36:01<09:54,  4.57s/it]

  [done]    Gui Santos — 460 shots

Fetching shot logs:  78%|███████████████▌    | 453/582 [36:05<09:25,  4.38s/it]

  [done]    Ben Saraf — 303 shots

Fetching shot logs:  78%|███████████████▌    | 454/582 [36:09<09:09,  4.30s/it]

  [done]    Dario Saric — 6 shots

Fetching shot logs:  78%|███████████████▋    | 455/582 [36:13<09:14,  4.37s/it]

  [done]    Alex Sarr — 656 shots

Fetching shot logs:  78%|███████████████▋    | 456/582 [36:18<09:36,  4.58s/it]

  [done]    Olivier Sarr — 7 shots

Fetching shot logs:  79%|███████████████▋    | 457/582 [36:23<09:41,  4.65s/it]

  [done]    Marcus Sasser — 177 shots

Fetching shot logs:  79%|███████████████▋    | 458/582 [36:28<09:29,  4.59s/it]

  [done]    Baylor Scheierman — 333 shots

Fetching shot logs:  79%|███████████████▊    | 459/582 [36:31<08:57,  4.37s/it]

  [done]    Dennis Schröder — 629 shots

Fetching shot logs:  79%|███████████████▊    | 460/582 [36:36<08:42,  4.29s/it]

  [done]    Trevon Scott — 50 shots

Fetching shot logs:  79%|███████████████▊    | 461/582 [36:40<08:40,  4.30s/it]

  [done]    Mark Sears — 13 shots

Fetching shot logs:  79%|███████████████▉    | 462/582 [36:44<08:24,  4.21s/it]

  [done]    Alperen Sengun — 1,123 shots

Fetching shot logs:  80%|███████████████▉    | 463/582 [36:48<08:24,  4.24s/it]

  [done]    Brice Sensabaugh — 857 shots

Fetching shot logs:  80%|███████████████▉    | 464/582 [36:53<08:28,  4.31s/it]

  [done]    Collin Sexton — 742 shots

Fetching shot logs:  80%|███████████████▉    | 465/582 [36:57<08:28,  4.34s/it]

  [done]    Landry Shamet — 364 shots

Fetching shot logs:  80%|████████████████    | 466/582 [37:02<08:51,  4.58s/it]

  [done]    Terrence Shannon Jr. — 171 shots

Fetching shot logs:  80%|████████████████    | 467/582 [37:06<08:22,  4.37s/it]

  [done]    Day'Ron Sharpe — 356 shots

Fetching shot logs:  80%|████████████████    | 468/582 [37:09<07:37,  4.01s/it]

  [done]    Shaedon Sharpe — 868 shots

Fetching shot logs:  81%|████████████████    | 469/582 [37:14<08:10,  4.34s/it]

  [done]    Jamal Shead — 504 shots

Fetching shot logs:  81%|████████████████▏   | 470/582 [37:18<07:31,  4.03s/it]

  [done]    Ben Sheppard — 387 shots

Fetching shot logs:  81%|████████████████▏   | 471/582 [37:22<07:32,  4.08s/it]

  [done]    Reed Sheppard — 946 shots

Fetching shot logs:  81%|████████████████▏   | 472/582 [37:26<07:19,  4.00s/it]

  [done]    Max Shulga — 8 shots

Fetching shot logs:  81%|████████████████▎   | 473/582 [37:31<07:52,  4.34s/it]

  [done]    Pascal Siakam — 1,155 shots

Fetching shot logs:  81%|████████████████▎   | 474/582 [37:34<07:26,  4.13s/it]

  [done]    Anfernee Simons — 648 shots

Fetching shot logs:  82%|████████████████▎   | 475/582 [37:38<06:58,  3.91s/it]

  [done]    KJ Simpson — 99 shots

Fetching shot logs:  82%|████████████████▎   | 476/582 [37:42<07:14,  4.10s/it]

  [done]    Jericho Sims — 185 shots

Fetching shot logs:  82%|████████████████▍   | 477/582 [37:47<07:39,  4.37s/it]

  [done]    Jalen Slawson — 77 shots

Fetching shot logs:  82%|████████████████▍   | 478/582 [37:53<08:17,  4.79s/it]

  [done]    Javon Small — 288 shots

Fetching shot logs:  82%|████████████████▍   | 479/582 [37:58<08:15,  4.81s/it]

  [done]    Marcus Smart — 476 shots

Fetching shot logs:  82%|████████████████▍   | 480/582 [38:03<08:11,  4.82s/it]

  [done]    Dru Smith — 325 shots

Fetching shot logs:  83%|████████████████▌   | 481/582 [38:07<07:56,  4.72s/it]

  [done]    Jalen Smith — 404 shots

Fetching shot logs:  83%|████████████████▌   | 482/582 [38:12<07:48,  4.68s/it]

  [done]    Malachi Smith — 99 shots

Fetching shot logs:  83%|████████████████▌   | 483/582 [38:16<07:22,  4.47s/it]

  [done]    Tolu Smith — 36 shots

Fetching shot logs:  83%|████████████████▋   | 484/582 [38:21<07:23,  4.53s/it]

  [done]    Tyler Smith — 50 shots

Fetching shot logs:  83%|████████████████▋   | 485/582 [38:24<06:57,  4.30s/it]

  [done]    Jabari Smith Jr. — 975 shots

Fetching shot logs:  84%|████████████████▋   | 486/582 [38:30<07:28,  4.67s/it]

  [done]    Nick Smith Jr. — 161 shots

Fetching shot logs:  84%|████████████████▋   | 487/582 [38:35<07:31,  4.75s/it]

  [done]    Jeremy Sochan — 129 shots

Fetching shot logs:  84%|████████████████▊   | 488/582 [38:38<06:52,  4.39s/it]

  [done]    Cam Spencer — 556 shots

Fetching shot logs:  84%|████████████████▊   | 489/582 [38:43<06:51,  4.42s/it]

  [done]    Pat Spencer — 436 shots

Fetching shot logs:  84%|████████████████▊   | 490/582 [38:46<06:17,  4.10s/it]

  [done]    Isaiah Stevens — 7 shots

Fetching shot logs:  84%|████████████████▊   | 491/582 [38:50<05:55,  3.91s/it]

  [done]    Isaiah Stewart — 402 shots

Fetching shot logs:  85%|████████████████▉   | 492/582 [38:54<06:10,  4.12s/it]

  [done]    Julian Strawther — 319 shots

Fetching shot logs:  85%|████████████████▉   | 493/582 [38:59<06:21,  4.28s/it]

  [done]    Max Strus — 106 shots

Fetching shot logs:  85%|████████████████▉   | 494/582 [39:03<06:05,  4.15s/it]

  [done]    Jalen Suggs — 649 shots

Fetching shot logs:  85%|█████████████████   | 495/582 [39:06<05:41,  3.92s/it]

  [done]    Jae'Sean Tate — 109 shots

Fetching shot logs:  85%|█████████████████   | 496/582 [39:11<06:01,  4.21s/it]

  [done]    Jayson Tatum — 287 shots

Fetching shot logs:  85%|█████████████████   | 497/582 [39:16<06:26,  4.55s/it]

  [done]    Jahmyl Telfort — 4 shots

Fetching shot logs:  86%|█████████████████   | 498/582 [39:21<06:31,  4.66s/it]

  [done]    Garrett Temple — 15 shots

Fetching shot logs:  86%|█████████████████▏  | 499/582 [39:26<06:32,  4.73s/it]

  [done]    Dalen Terry — 155 shots

Fetching shot logs:  86%|█████████████████▏  | 500/582 [39:30<06:01,  4.40s/it]

  [done]    Adou Thiero — 31 shots

Fetching shot logs:  86%|█████████████████▏  | 501/582 [39:35<06:03,  4.48s/it]

  [done]    Cam Thomas — 461 shots

Fetching shot logs:  86%|█████████████████▎  | 502/582 [39:38<05:45,  4.31s/it]

  [done]    Amen Thompson — 1,044 shots

Fetching shot logs:  86%|█████████████████▎  | 503/582 [39:43<05:47,  4.40s/it]

  [done]    Ausar Thompson — 577 shots

Fetching shot logs:  87%|█████████████████▎  | 504/582 [39:47<05:28,  4.21s/it]

  [done]    Ethan Thompson — 196 shots

Fetching shot logs:  87%|█████████████████▎  | 505/582 [39:51<05:33,  4.33s/it]

  [done]    Klay Thompson — 728 shots

Fetching shot logs:  87%|█████████████████▍  | 506/582 [39:56<05:31,  4.37s/it]

  [done]    Matisse Thybulle — 134 shots

Fetching shot logs:  87%|█████████████████▍  | 507/582 [39:59<05:04,  4.06s/it]

  [done]    Xavier Tillman — 46 shots

Fetching shot logs:  87%|█████████████████▍  | 508/582 [40:04<05:14,  4.25s/it]

  [done]    Drew Timme — 66 shots

Fetching shot logs:  87%|█████████████████▍  | 509/582 [40:08<05:09,  4.24s/it]

  [done]    Nae'Qwan Tomlin — 314 shots

Fetching shot logs:  88%|█████████████████▌  | 510/582 [40:13<05:13,  4.35s/it]

  [done]    John Tonje — 14 shots

Fetching shot logs:  88%|█████████████████▌  | 511/582 [40:17<05:12,  4.40s/it]

  [done]    Nikola Topić — 51 shots

Fetching shot logs:  88%|█████████████████▌  | 512/582 [40:22<05:08,  4.40s/it]

  [done]    Jacob Toppin — 6 shots

Fetching shot logs:  88%|█████████████████▋  | 513/582 [40:26<05:02,  4.38s/it]

  [done]    Obi Toppin — 199 shots

Fetching shot logs:  88%|█████████████████▋  | 514/582 [40:30<04:41,  4.14s/it]

  [done]    Karl-Anthony Towns — 1,032 shots

Fetching shot logs:  88%|█████████████████▋  | 515/582 [40:34<04:50,  4.33s/it]

  [done]    Nolan Traore — 479 shots

Fetching shot logs:  89%|█████████████████▋  | 516/582 [40:38<04:33,  4.15s/it]

  [done]    Luke Travers — 36 shots

Fetching shot logs:  89%|█████████████████▊  | 517/582 [40:42<04:33,  4.21s/it]

  [done]    Gary Trent Jr. — 473 shots

Fetching shot logs:  89%|█████████████████▊  | 518/582 [40:47<04:42,  4.41s/it]

  [done]    Oscar Tshiebwe — 145 shots

Fetching shot logs:  89%|█████████████████▊  | 519/582 [40:52<04:46,  4.55s/it]

  [done]    Myles Turner — 646 shots

Fetching shot logs:  89%|█████████████████▊  | 520/582 [40:55<04:17,  4.16s/it]

  [done]    Hunter Tyson — 52 shots

Fetching shot logs:  90%|█████████████████▉  | 521/582 [41:00<04:28,  4.40s/it]

  [done]    Jaylon Tyson — 670 shots

Fetching shot logs:  90%|█████████████████▉  | 522/582 [41:05<04:31,  4.52s/it]

  [done]    Stanley Umude — 2 shots

Fetching shot logs:  90%|█████████████████▉  | 523/582 [41:10<04:33,  4.63s/it]

  [done]    Jonas Valančiūnas — 390 shots

Fetching shot logs:  90%|██████████████████  | 524/582 [41:13<04:06,  4.26s/it]

  [done]    Jarred Vanderbilt — 240 shots

Fetching shot logs:  90%|██████████████████  | 525/582 [41:19<04:17,  4.52s/it]

  [done]    Devin Vassell — 755 shots

Fetching shot logs:  90%|██████████████████  | 526/582 [41:24<04:21,  4.68s/it]

  [done]    Gabe Vincent — 216 shots

Fetching shot logs:  91%|██████████████████  | 527/582 [41:28<04:10,  4.55s/it]

  [done]    Tristan Vukcevic — 317 shots

Fetching shot logs:  91%|██████████████████▏ | 528/582 [41:31<03:47,  4.21s/it]

  [done]    Nikola Vučević — 799 shots

Fetching shot logs:  91%|██████████████████▏ | 529/582 [41:36<03:43,  4.22s/it]

  [done]    Dean Wade — 278 shots

Fetching shot logs:  91%|██████████████████▏ | 530/582 [41:40<03:36,  4.16s/it]

  [done]    Franz Wagner — 507 shots

Fetching shot logs:  91%|██████████████████▏ | 531/582 [41:44<03:42,  4.36s/it]

  [done]    Moritz Wagner — 195 shots

Fetching shot logs:  91%|██████████████████▎ | 532/582 [41:48<03:27,  4.15s/it]

  [done]    Jabari Walker — 213 shots

Fetching shot logs:  92%|██████████████████▎ | 533/582 [41:52<03:14,  3.98s/it]

  [done]    Jarace Walker — 733 shots

Fetching shot logs:  92%|██████████████████▎ | 534/582 [41:57<03:26,  4.30s/it]

  [done]    Cason Wallace — 584 shots

Fetching shot logs:  92%|██████████████████▍ | 535/582 [42:02<03:33,  4.55s/it]

  [done]    Keaton Wallace — 171 shots

Fetching shot logs:  92%|██████████████████▍ | 536/582 [42:05<03:15,  4.25s/it]

  [done]    Jordan Walsh — 267 shots

Fetching shot logs:  92%|██████████████████▍ | 537/582 [42:10<03:18,  4.42s/it]

  [done]    Ja'Kobe Walter — 404 shots

Fetching shot logs:  92%|██████████████████▍ | 538/582 [42:15<03:22,  4.61s/it]

  [done]    Kel'el Ware — 649 shots

Fetching shot logs:  93%|██████████████████▌ | 539/582 [42:20<03:16,  4.57s/it]

  [done]    P.J. Washington — 658 shots

Fetching shot logs:  93%|██████████████████▌ | 540/582 [42:23<02:58,  4.24s/it]

  [done]    TyTy Washington Jr. — 19 shots

Fetching shot logs:  93%|██████████████████▌ | 541/582 [42:28<03:02,  4.45s/it]

  [done]    Lindy Waters III — 88 shots

Fetching shot logs:  93%|██████████████████▋ | 542/582 [42:33<03:05,  4.65s/it]

  [done]    Trendon Watford — 268 shots

Fetching shot logs:  93%|██████████████████▋ | 543/582 [42:39<03:12,  4.93s/it]

  [done]    Jamir Watkins — 296 shots

Fetching shot logs:  93%|██████████████████▋ | 544/582 [42:42<02:52,  4.55s/it]

  [done]    Peyton Watson — 581 shots

Fetching shot logs:  94%|██████████████████▋ | 545/582 [42:46<02:37,  4.25s/it]

  [done]    Jaylen Wells — 698 shots

Fetching shot logs:  94%|██████████████████▊ | 546/582 [42:51<02:40,  4.45s/it]

  [done]    Victor Wembanyama — 1,080 shots

Fetching shot logs:  94%|██████████████████▊ | 547/582 [42:56<02:43,  4.66s/it]

  [done]    Blake Wesley — 124 shots

Fetching shot logs:  94%|██████████████████▊ | 548/582 [43:01<02:37,  4.62s/it]

  [done]    Russell Westbrook — 839 shots

Fetching shot logs:  94%|██████████████████▊ | 549/582 [43:05<02:32,  4.61s/it]

  [done]    Coby White — 623 shots

Fetching shot logs:  95%|██████████████████▉ | 550/582 [43:10<02:27,  4.60s/it]

  [done]    Derrick White — 1,108 shots

Fetching shot logs:  95%|██████████████████▉ | 551/582 [43:14<02:23,  4.63s/it]

  [done]    Dariq Whitehead — 93 shots

Fetching shot logs:  95%|██████████████████▉ | 552/582 [43:18<02:09,  4.33s/it]

  [done]    Cam Whitmore — 169 shots

Fetching shot logs:  95%|███████████████████ | 553/582 [43:23<02:11,  4.52s/it]

  [done]    Aaron Wiggins — 536 shots

Fetching shot logs:  95%|███████████████████ | 554/582 [43:27<02:01,  4.36s/it]

  [done]    Andrew Wiggins — 821 shots

Fetching shot logs:  95%|███████████████████ | 555/582 [43:32<02:02,  4.53s/it]

  [done]    Alondes Williams — 26 shots

Fetching shot logs:  96%|███████████████████ | 556/582 [43:36<01:57,  4.53s/it]

  [done]    Amari Williams — 20 shots

Fetching shot logs:  96%|███████████████████▏| 557/582 [43:40<01:43,  4.15s/it]

  [done]    Brandon Williams — 617 shots

Fetching shot logs:  96%|███████████████████▏| 558/582 [43:45<01:45,  4.38s/it]

  [done]    Cody Williams — 509 shots

Fetching shot logs:  96%|███████████████████▏| 559/582 [43:49<01:38,  4.30s/it]

  [done]    Grant Williams — 183 shots

Fetching shot logs:  96%|███████████████████▏| 560/582 [43:52<01:29,  4.09s/it]

  [done]    Jalen Williams — 446 shots

Fetching shot logs:  96%|███████████████████▎| 561/582 [43:56<01:19,  3.81s/it]

  [done]    Jaylin Williams — 352 shots

Fetching shot logs:  97%|███████████████████▎| 562/582 [44:00<01:17,  3.87s/it]

  [done]    Kenrich Williams — 296 shots

Fetching shot logs:  97%|███████████████████▎| 563/582 [44:03<01:13,  3.87s/it]

  [done]    Mark Williams — 438 shots

Fetching shot logs:  97%|███████████████████▍| 564/582 [44:08<01:15,  4.22s/it]

  [done]    Nate Williams — 88 shots

Fetching shot logs:  97%|███████████████████▍| 565/582 [44:13<01:14,  4.37s/it]

  [done]    Patrick Williams — 478 shots

Fetching shot logs:  97%|███████████████████▍| 566/582 [44:17<01:09,  4.32s/it]

  [done]    Ziaire Williams — 433 shots

Fetching shot logs:  97%|███████████████████▍| 567/582 [44:22<01:04,  4.31s/it]

  [done]    Robert Williams III — 250 shots

Fetching shot logs:  98%|███████████████████▌| 568/582 [44:25<00:56,  4.03s/it]

  [done]    Vince Williams Jr. — 292 shots

Fetching shot logs:  98%|███████████████████▌| 569/582 [44:30<00:56,  4.33s/it]

  [done]    Lucas Williamson — 75 shots

Fetching shot logs:  98%|███████████████████▌| 570/582 [44:35<00:53,  4.49s/it]

  [done]    Zion Williamson — 807 shots

Fetching shot logs:  98%|███████████████████▌| 571/582 [44:39<00:46,  4.23s/it]

  [done]    Jalen Wilson — 278 shots

Fetching shot logs:  98%|███████████████████▋| 572/582 [44:42<00:40,  4.06s/it]

  [done]    James Wiseman — 10 shots

Fetching shot logs:  98%|███████████████████▋| 573/582 [44:48<00:42,  4.69s/it]

  [done]    Danny Wolf — 440 shots

Fetching shot logs:  99%|███████████████████▋| 574/582 [44:53<00:37,  4.75s/it]

  [done]    Guerschon Yabusele — 312 shots

Fetching shot logs:  99%|███████████████████▊| 575/582 [45:00<00:37,  5.29s/it]

  [done]    Yang Hansen — 100 shots

Fetching shot logs:  99%|███████████████████▊| 576/582 [45:05<00:30,  5.16s/it]

  [done]    Jahmir Young — 25 shots

Fetching shot logs:  99%|███████████████████▊| 577/582 [45:09<00:25,  5.02s/it]

  [done]    Trae Young — 177 shots

Fetching shot logs:  99%|███████████████████▊| 578/582 [45:17<00:23,  5.85s/it]

  [done]    Chris Youngblood — 63 shots

Fetching shot logs:  99%|███████████████████▉| 579/582 [45:20<00:15,  5.08s/it]

  [done]    Omer Yurtseven — 26 shots

Fetching shot logs: 100%|███████████████████▉| 580/582 [45:26<00:10,  5.17s/it]

  [done]    Rocco Zikarsky — 8 shots

Fetching shot logs: 100%|███████████████████▉| 581/582 [45:29<00:04,  4.69s/it]

  [done]    Ivica Zubac — 482 shots

Fetching shot logs: 100%|████████████████████| 582/582 [45:35<00:00,  4.70s/it]

  [done]    Tristan da Silva — 620 shots

Loop complete.
  Loaded from cache : 1
  Fetched via API   : 581
  Successful        : 582
  Skipped (0 shots) : 0
  Failed            : 0

### 2.3 — Retry Failed Players

If any players ended up in `failed_players`, we make one more pass at them here. A player who failed during the main loop likely hit a brief NBA.com outage — a fresh attempt a few minutes later usually succeeds. We use a longer fixed delay (8 seconds) for these retries to give the API more breathing room.

If `failed_players` is empty, this cell does nothing and can be skipped.

In [9]:
if not failed_players:
    print("No failed players — nothing to retry.")
else:
    print(f"Retrying {len(failed_players)} failed player(s)...\n")
    still_failed = []

    for entry in failed_players:
        name, player_id = entry["name"], entry["id"]
        print(f"  Retrying {name}...")
        time.sleep(8.0)

        df = fetch_shot_log(player_id=player_id, season=SEASON)

        if df is None:
            still_failed.append(entry)
            print(f"    [FAILED again] {name}")
        elif len(df) == 0:
            print(f"    [skip] {name} — 0 shots")
        else:
            df["NAME"] = name
            all_shot_logs.append(df)
            print(f"    [recovered] {name} — {len(df):,} shots")

    failed_players = still_failed
    print(f"\nAfter retry — still failed: {len(failed_players)}")
    if failed_players:
        print("Permanently failed players:")
        for entry in failed_players:
            print(f"  {entry['name']} (ID: {entry['id']})")

No failed players — nothing to retry.

### 2.4 — Combine and Save to `data/raw/`

We stack all per-player DataFrames into one combined DataFrame and save it to `data/raw/shots_2025_26.csv`. This is the raw source of truth for the rest of the project — notebook 02 reads from here and all cleaning happens downstream.

If `all_shot_logs` is empty (every player failed), we print a warning and stop rather than writing an empty file.

In [10]:
if not all_shot_logs:
    print("ERROR: all_shot_logs is empty — no data to save. Check failed_players and retry.")
else:
    combined_shots = pd.concat(all_shot_logs, ignore_index=True)

    raw_output_path = RAW_DIR / "shots_2025_26.csv"
    combined_shots.to_csv(raw_output_path, index=False)

    print(f"Saved  : {raw_output_path}")
    print(f"Rows   : {len(combined_shots):,}")
    print(f"Cols   : {len(combined_shots.columns)}")
    print(f"Players: {combined_shots['NAME'].nunique():,}")

Saved  : /Users/narayanlekhi/Documents/GitHub/nba-shot-analytics/data/raw/shots_2025_26.csv
Rows   : 219,160
Cols   : 25
Players: 582

### 2.5 — Final Summary

A quick verification that the combined dataset looks reasonable: player count, shot count distribution, and a top-10 by volume. We also print the failed player list one final time so it's visible in the notebook's output history.

In [11]:
shots_per_player = (
    combined_shots.groupby("NAME")
    .size()
    .rename("FGA")
    .sort_values(ascending=False)
)

print(f"=== 2025-26 Shot Log Summary ===")
print(f"Players      : {len(shots_per_player):,}")
print(f"Total FGA    : {shots_per_player.sum():,}")
print(f"Median FGA   : {shots_per_player.median():.0f} per player")
print(f"Min FGA      : {shots_per_player.min()} ({shots_per_player.idxmin()})")
print(f"Max FGA      : {shots_per_player.max()} ({shots_per_player.idxmax()})")

print(f"\nTop 10 by shot volume:")
display(shots_per_player.head(10).reset_index())

print(f"\nFailed players (excluded from CSV): {len(failed_players)}")
for entry in failed_players:
    print(f"  {entry['name']} (ID: {entry['id']})")
if not failed_players:
    print("  None — full dataset is complete.")

=== 2025-26 Shot Log Summary ===
Players      : 582
Total FGA    : 219,160
Median FGA   : 292 per player
Min FGA      : 1 (Tosan Evbuomwan)
Max FGA      : 1543 (Jaylen Brown)

Top 10 by shot volume:

                      NAME   FGA
0             Jaylen Brown  1543
1             Tyrese Maxey  1501
2            Jalen Brunson  1475
3              Luka Dončić  1457
4         Donovan Mitchell  1403
5             Kevin Durant  1376
6             Jamal Murray  1360
7  Shai Gilgeous-Alexander  1321
8           Brandon Ingram  1288
9            Kawhi Leonard  1258

Failed players (excluded from CSV): 0
  None — full dataset is complete.

## Section 3 — Pivot Verification: Contest Data and Qualifying Player Pool

Before building the new PPS-based analysis, we need to confirm two things directly from the raw data:

1. **`CLOSE_DEF_DIST`** — does this column exist in `shots_2025_26.csv`? If yes, how complete is it and what does the distribution look like so we can validate that the contest buckets (0–2 ft, 2–4 ft, 4–6 ft, 6+ ft) are meaningful?
2. **300-shot minimum filter** — how many players in the 2025–26 raw data have at least 300 field goal attempts, and how many fall below that threshold?

Both checks must be confirmed here before any downstream notebooks are updated.

In [12]:
import pandas as pd
from pathlib import Path

# Re-declare paths so this works after a kernel restart
NOTEBOOK_DIR = Path().resolve()
PROJECT_ROOT = NOTEBOOK_DIR.parent
RAW_FILE     = PROJECT_ROOT / "data" / "raw" / "shots_2025_26.csv"

raw = pd.read_csv(RAW_FILE)

# ── Check 1: Does CLOSE_DEF_DIST exist in the raw data? ──────────────────
print("=" * 60)
print("CHECK 1 — CLOSE_DEF_DIST column")
print("=" * 60)

DIST_COL = "CLOSE_DEF_DIST"

if DIST_COL not in raw.columns:
    # Column is missing — explain why and what it would take to get it.
    # ShotChartDetail with context_measure_simple='FGA' returns shot location
    # and outcome only. To get defender distance we need 'DFGA' (defended FGA),
    # which returns a different result set including CLOSE_DEF_DIST.
    print(f"\n  COLUMN NOT FOUND: '{DIST_COL}' is not in shots_2025_26.csv")
    print(f"\n  The current raw file has {len(raw.columns)} columns:")
    for col in raw.columns:
        print(f"    {col}")
    print()
    print("  WHY IT IS MISSING:")
    print("  Notebook 01 fetches with context_measure_simple='FGA'.")
    print("  That returns shot coordinates + outcome, but NOT defender data.")
    print("  To get CLOSE_DEF_DIST, the fetch must use context_measure_simple='DFGA'.")
    print("  The raw data needs to be re-collected before the contest-level")
    print("  breakdown can be implemented.")

else:
    # Column exists — print completeness and distribution.
    n_total   = len(raw)
    n_null    = raw[DIST_COL].isna().sum()
    n_filled  = n_total - n_null
    pct_fill  = n_filled / n_total * 100

    print(f"\n  Column found in raw data.")
    print(f"\n  Row completeness:")
    print(f"    Total rows        : {n_total:,}")
    print(f"    Rows with value   : {n_filled:,}  ({pct_fill:.1f}%)")
    print(f"    Rows null/missing : {n_null:,}  ({100 - pct_fill:.1f}%)")

    filled = raw[DIST_COL].dropna()
    print(f"\n  Distribution of CLOSE_DEF_DIST (in feet):")
    print(f"    Min    : {filled.min():.2f} ft")
    print(f"    Max    : {filled.max():.2f} ft")
    print(f"    Mean   : {filled.mean():.2f} ft")
    print(f"    Median : {filled.median():.2f} ft")
    print(f"    Std    : {filled.std():.2f} ft")

    # Show how many shots fall into each proposed contest bucket.
    # Buckets: 0-2 ft (heavily contested), 2-4 ft (contested),
    #          4-6 ft (open), 6+ ft (wide open)
    bins   = [0, 2, 4, 6, float("inf")]
    labels = [
        "Heavily Contested (0-2 ft)",
        "Contested         (2-4 ft)",
        "Open              (4-6 ft)",
        "Wide Open          (6+ ft)",
    ]
    buckets = pd.cut(filled, bins=bins, labels=labels, right=False)

    print(f"\n  Shot counts by proposed contest bucket:")
    for label, count in buckets.value_counts().sort_index().items():
        pct = count / n_filled * 100
        print(f"    {label} : {count:>7,}  ({pct:.1f}%)")

============================================================
CHECK 1 — CLOSE_DEF_DIST column
============================================================

  COLUMN NOT FOUND: 'CLOSE_DEF_DIST' is not in shots_2025_26.csv

  The current raw file has 25 columns:
    GRID_TYPE
    GAME_ID
    GAME_EVENT_ID
    PLAYER_ID
    PLAYER_NAME
    TEAM_ID
    TEAM_NAME
    PERIOD
    MINUTES_REMAINING
    SECONDS_REMAINING
    EVENT_TYPE
    ACTION_TYPE
    SHOT_TYPE
    SHOT_ZONE_BASIC
    SHOT_ZONE_AREA
    SHOT_ZONE_RANGE
    SHOT_DISTANCE
    LOC_X
    LOC_Y
    SHOT_ATTEMPTED_FLAG
    SHOT_MADE_FLAG
    GAME_DATE
    HTM
    VTM
    NAME

  WHY IT IS MISSING:
  Notebook 01 fetches with context_measure_simple='FGA'.
  That returns shot coordinates + outcome, but NOT defender data.
  To get CLOSE_DEF_DIST, the fetch must use context_measure_simple='DFGA'.
  The raw data needs to be re-collected before the contest-level
  breakdown can be implemented.

In [13]:
# ── Check 2: 300-shot minimum filter ─────────────────────────────────────
# Any player with fewer than 300 total field goal attempts in the 2025-26
# season will be excluded from the PPS analysis. This ensures every player
# in the dataset has a large enough sample for zone-level conclusions.
print("=" * 60)
print("CHECK 2 — 300-Shot Minimum Filter")
print("=" * 60)

MIN_FGA = 300

# Count total shot attempts per player across all games and zones
shots_per_player = (
    raw.groupby("NAME")
    .size()
    .rename("FGA")
    .sort_values(ascending=False)
)

total_players = len(shots_per_player)
qualifying    = (shots_per_player >= MIN_FGA).sum()
excluded      = total_players - qualifying

print(f"\n  Minimum FGA threshold        : {MIN_FGA}")
print(f"  Total players in raw data    : {total_players:,}")
print(f"  Players with >= {MIN_FGA} FGA   : {qualifying:,}  (qualify for analysis)")
print(f"  Players with  < {MIN_FGA} FGA   : {excluded:,}  (excluded — insufficient sample)")

print(f"\n  Shot count distribution across all {total_players} players:")
print(f"    Min    : {shots_per_player.min():.0f}  ({shots_per_player.idxmin()})")
print(f"    Median : {shots_per_player.median():.0f}")
print(f"    Mean   : {shots_per_player.mean():.0f}")
print(f"    Max    : {shots_per_player.max():.0f}  ({shots_per_player.idxmax()})")

print(f"\n  Top 10 qualifying players by FGA:")
print(f"  {'Player':<30} {'FGA':>6}")
print(f"  {'-'*30} {'------':>6}")
for name, fga in shots_per_player.head(10).items():
    print(f"  {name:<30} {fga:>6,}")

print(f"\n  Bottom 10 qualifying players (just above the {MIN_FGA}-shot cutoff):")
qualifying_players = shots_per_player[shots_per_player >= MIN_FGA]
print(f"  {'Player':<30} {'FGA':>6}")
print(f"  {'-'*30} {'------':>6}")
for name, fga in qualifying_players.tail(10).items():
    print(f"  {name:<30} {fga:>6,}")

============================================================
CHECK 2 — 300-Shot Minimum Filter
============================================================

  Minimum FGA threshold        : 300
  Total players in raw data    : 582
  Players with >= 300 FGA   : 284  (qualify for analysis)
  Players with  < 300 FGA   : 298  (excluded — insufficient sample)

  Shot count distribution across all 582 players:
    Min    : 1  (Tosan Evbuomwan)
    Median : 292
    Mean   : 377
    Max    : 1543  (Jaylen Brown)

  Top 10 qualifying players by FGA:
  Player                            FGA
  ------------------------------ ------
  Jaylen Brown                    1,543
  Tyrese Maxey                    1,501
  Jalen Brunson                   1,475
  Luka Dončić                     1,457
  Donovan Mitchell                1,403
  Kevin Durant                    1,376
  Jamal Murray                    1,360
  Shai Gilgeous-Alexander         1,321
  Brandon Ingram                  1,288
  Kawhi Leonard                   1,258

  Bottom 10 qualifying players (just above the 300-shot cutoff):
  Player                            FGA
  ------------------------------ ------
  Nikola Jović                      314
  Nae'Qwan Tomlin                   314
  Rayan Rupert                      313
  Guerschon Yabusele                312
  Jakob Poeltl                      310
  Jevon Carter                      307
  Ben Saraf                         303
  Tre Mann                          303
  Keegan Murray                     300
  Alex Caruso                       300

In [14]:
import pandas as pd
df = pd.read_csv('../data/raw/shots_2025_26.csv')
print(df.columns.tolist())

['GRID_TYPE', 'GAME_ID', 'GAME_EVENT_ID', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_NAME', 'PERIOD', 'MINUTES_REMAINING', 'SECONDS_REMAINING', 'EVENT_TYPE', 'ACTION_TYPE', 'SHOT_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'SHOT_DISTANCE', 'LOC_X', 'LOC_Y', 'SHOT_ATTEMPTED_FLAG', 'SHOT_MADE_FLAG', 'GAME_DATE', 'HTM', 'VTM', 'NAME']

In [3]:
import time
import random
from nba_api.stats.endpoints import ShotChartDetail, PlayerDashPtShots

# Stephen Curry's NBA player ID
CURRY_ID = 1629029
SEASON   = "2025-26"

# ── Part 1: Test ShotChartDetail with multiple context_measure_simple values ──
# The current notebook uses context_measure_simple="FGA".
# We test every documented valid value to confirm whether any of them
# returns a CLOSE_DEF_DIST column at the individual shot level.

print("=" * 65)
print("PART 1 — ShotChartDetail: searching for CLOSE_DEF_DIST")
print("=" * 65)

context_measures = ["FGA", "FGM", "PTS", "FG3A"]

for ctx in context_measures:
    try:
        sc = ShotChartDetail(
            team_id=0,
            player_id=CURRY_ID,
            season_nullable=SEASON,
            season_type_all_star="Regular Season",
            context_measure_simple=ctx,
        )
        # ShotChartDetail returns two result sets:
        #   [0] = shot-by-shot rows
        #   [1] = pre-computed league zone averages (fewer rows, different columns)
        result_sets = sc.get_data_frames()

        for idx, df in enumerate(result_sets):
            has_dist = "CLOSE_DEF_DIST" in df.columns
            print(
                f"  context={ctx:<6}  result_set[{idx}]  "
                f"rows={len(df):>4}  cols={len(df.columns):>3}  "
                f"CLOSE_DEF_DIST={has_dist}"
            )
            if has_dist:
                print(f"    First 5 values: {df['CLOSE_DEF_DIST'].head().tolist()}")

        time.sleep(random.uniform(2.5, 4.0))   # rate-limit courtesy delay

    except Exception as e:
        print(f"  context={ctx:<6}  ERROR: {type(e).__name__}: {e}")

print()

# Print full column list from the standard FGA result set so we see exactly
# what ShotChartDetail does return
print("Full column list from ShotChartDetail (context=FGA, result_set[0]):")
try:
    sc_fga = ShotChartDetail(
        team_id=0,
        player_id=CURRY_ID,
        season_nullable=SEASON,
        season_type_all_star="Regular Season",
        context_measure_simple="FGA",
    )
    df_fga = sc_fga.get_data_frames()[0]
    for col in df_fga.columns:
        print(f"  {col}")
    print(f"\n  Total: {len(df_fga.columns)} columns — CLOSE_DEF_DIST present: {'CLOSE_DEF_DIST' in df_fga.columns}")
except Exception as e:
    print(f"  ERROR: {type(e).__name__}: {e}")

time.sleep(random.uniform(2.5, 4.0))

# ── Part 2: Test PlayerDashPtShots — the tracking endpoint that has ───────
# defender-distance data, but in pre-aggregated bucketed form (not per-shot)
print()
print("=" * 65)
print("PART 2 — PlayerDashPtShots: CLOSE_DEF_DIST_RANGE (aggregated)")
print("=" * 65)

try:
    ep = PlayerDashPtShots(
        player_id=CURRY_ID,
        team_id=0,
        season=SEASON,
        season_type_all_star="Regular Season",
    )
    dfs = ep.get_data_frames()
    print(f"\n  PlayerDashPtShots returned {len(dfs)} result sets:")

    for i, df in enumerate(dfs):
        # Check which result set has the distance range
        dist_col = "CLOSE_DEF_DIST_RANGE" if "CLOSE_DEF_DIST_RANGE" in df.columns else None
        marker = "  <-- DISTANCE DATA" if dist_col else ""
        print(f"  [{i}] {df.shape[0]} rows x {df.shape[1]} cols{marker}")

    # Print the distance-range result set in full
    # (result sets [4] and [5] both have CLOSE_DEF_DIST_RANGE — 2PT and 3PT splits)
    for i, df in enumerate(dfs):
        if "CLOSE_DEF_DIST_RANGE" in df.columns:
            print(f"\n  Result set [{i}] — full contents (CLOSE_DEF_DIST_RANGE):")
            display_cols = ["CLOSE_DEF_DIST_RANGE", "FGA", "FGM", "FG_PCT", "EFG_PCT",
                            "FG2A", "FG2M", "FG2_PCT", "FG3A", "FG3M", "FG3_PCT"]
            available = [c for c in display_cols if c in df.columns]
            print(df[available].to_string(index=False))

except Exception as e:
    print(f"\n  ERROR: {type(e).__name__}: {e}")

# ── Summary ────────────────────────────────────────────────────────────────
print()
print("=" * 65)
print("SUMMARY")
print("=" * 65)
print("""
  ShotChartDetail (any context_measure_simple):
    Returns per-shot rows, but CLOSE_DEF_DIST is NOT available.
    The 24-column schema contains location and outcome only.

  PlayerDashPtShots (result sets [4] and [5]):
    Returns CLOSE_DEF_DIST_RANGE — pre-bucketed aggregates.
    Each row = one distance bucket (e.g. '0-2 Feet - Very Tight').
    Each row has FGA, FGM, FG_PCT, EFG_PCT for that bucket.
    This is NOT per-shot data — it is a summary table per player.

  IMPLICATION:
    Per-shot CLOSE_DEF_DIST is not exposed by the NBA stats API.
    The closest available data is CLOSE_DEF_DIST_RANGE from
    PlayerDashPtShots, which gives bucketed efficiency breakdowns
    (FGA/EFG% per distance range) at the player level — not the
    shot level. This is enough to show how a player performs under
    different contest conditions, but it cannot be joined onto
    individual shot rows in shots_2025_26.csv.
""")

=================================================================
PART 1 — ShotChartDetail: searching for CLOSE_DEF_DIST
=================================================================
  context=FGA     result_set[0]  rows=1457  cols= 24  CLOSE_DEF_DIST=False
  context=FGA     result_set[1]  rows=  20  cols=  7  CLOSE_DEF_DIST=False
  context=FGM     result_set[0]  rows=1457  cols= 24  CLOSE_DEF_DIST=False
  context=FGM     result_set[1]  rows=  20  cols=  7  CLOSE_DEF_DIST=False
  context=PTS     result_set[0]  rows= 693  cols= 24  CLOSE_DEF_DIST=False
  context=PTS     result_set[1]  rows=  20  cols=  7  CLOSE_DEF_DIST=False
  context=FG3A    result_set[0]  rows= 694  cols= 24  CLOSE_DEF_DIST=False
  context=FG3A    result_set[1]  rows=  10  cols=  7  CLOSE_DEF_DIST=False

Full column list from ShotChartDetail (context=FGA, result_set[0]):
  GRID_TYPE
  GAME_ID
  GAME_EVENT_ID
  PLAYER_ID
  PLAYER_NAME
  TEAM_ID
  TEAM_NAME
  PERIOD
  MINUTES_REMAINING
  SECONDS_REMAINING
  EVENT_TYPE
  ACTION_TYPE
  SHOT_TYPE
  SHOT_ZONE_BASIC
  SHOT_ZONE_AREA
  SHOT_ZONE_RANGE
  SHOT_DISTANCE
  LOC_X
  LOC_Y
  SHOT_ATTEMPTED_FLAG
  SHOT_MADE_FLAG
  GAME_DATE
  HTM
  VTM

  Total: 24 columns — CLOSE_DEF_DIST present: False

=================================================================
PART 2 — PlayerDashPtShots: CLOSE_DEF_DIST_RANGE (aggregated)
=================================================================

  PlayerDashPtShots returned 7 result sets:
  [0] 1 rows x 19 cols
  [1] 4 rows x 19 cols
  [2] 6 rows x 19 cols
  [3] 5 rows x 19 cols
  [4] 4 rows x 19 cols  <-- DISTANCE DATA
  [5] 4 rows x 19 cols  <-- DISTANCE DATA
  [6] 3 rows x 19 cols

  Result set [4] — full contents (CLOSE_DEF_DIST_RANGE):
 CLOSE_DEF_DIST_RANGE  FGA  FGM  FG_PCT  EFG_PCT  FG2A  FG2M  FG2_PCT  FG3A  FG3M  FG3_PCT
0-2 Feet - Very Tight   53   28   0.528    0.538    50    27    0.540     3     1    0.333
     2-4 Feet - Tight  520  282   0.542    0.590   391   232    0.593   129    50    0.388
      4-6 Feet - Open  742  317   0.427    0.532   291   162    0.557   451   155    0.344
  6+ Feet - Wide Open  141   66   0.468    0.638    31    18    0.581   110    48    0.436

  Result set [5] — full contents (CLOSE_DEF_DIST_RANGE):
 CLOSE_DEF_DIST_RANGE  FGA  FGM  FG_PCT  EFG_PCT  FG2A  FG2M  FG2_PCT  FG3A  FG3M  FG3_PCT
0-2 Feet - Very Tight   27   15   0.556    0.574    24    14    0.583     3     1    0.333
     2-4 Feet - Tight  287  132   0.460    0.547   158    82    0.519   129    50    0.388
      4-6 Feet - Open  668  267   0.400    0.516   217   112    0.516   451   155    0.344
  6+ Feet - Wide Open  130   57   0.438    0.623    20     9    0.450   110    48    0.436

=================================================================
SUMMARY
=================================================================

  ShotChartDetail (any context_measure_simple):
    Returns per-shot rows, but CLOSE_DEF_DIST is NOT available.
    The 24-column schema contains location and outcome only.

  PlayerDashPtShots (result sets [4] and [5]):
    Returns CLOSE_DEF_DIST_RANGE — pre-bucketed aggregates.
    Each row = one distance bucket (e.g. '0-2 Feet - Very Tight').
    Each row has FGA, FGM, FG_PCT, EFG_PCT for that bucket.
    This is NOT per-shot data — it is a summary table per player.

  IMPLICATION:
    Per-shot CLOSE_DEF_DIST is not exposed by the NBA stats API.
    The closest available data is CLOSE_DEF_DIST_RANGE from
    PlayerDashPtShots, which gives bucketed efficiency breakdowns
    (FGA/EFG% per distance range) at the player level — not the
    shot level. This is enough to show how a player performs under
    different contest conditions, but it cannot be joined onto
    individual shot rows in shots_2025_26.csv.